/**
 * Platform audit event types (pure). Writer lives in platform-audit.server.ts.
 */
export const PLATFORM_AUDIT_EVENT_TYPES = [
  "SUPER_OWNER_ROLE_GRANTED",
  "SUPER_OWNER_ROLE_REVOKED",
  "SUPER_ADMIN_ROLE_GRANTED",
  "SUPER_ADMIN_ROLE_REVOKED",
  "SUPER_ADMIN_TENANT_GRANTED",
  "SUPER_ADMIN_TENANT_REVOKED",
  "TENANT_CREATED",
  "PLATFORM_TENANT_ENTRY_STARTED",
  "PLATFORM_TENANT_ENTRY_ENDED",
  "PLATFORM_TENANT_ENTRY_DENIED",
  "TENANT_OWNER_INVITED",
  "TENANT_OWNER_ADDED",
  "TENANT_OWNER_REMOVED",
  "TENANT_OWNER_ROLE_CHANGED",
  "LAST_TENANT_OWNER_ACTION_DENIED",
  "PLATFORM_ADMIN_INVITED",
  "PLATFORM_ADMIN_INVITE_CANCELLED",
  "PLATFORM_ROLE_GRANTED",
  "PLATFORM_ROLE_CHANGED",
  "PLATFORM_ROLE_REVOKED",
  "LAST_PLATFORM_OWNER_ACTION_DENIED",
  "SUPER_ADMIN_GRANT_CREATED",
  "SUPER_ADMIN_GRANT_CHANGED",
  "SUPER_ADMIN_GRANT_REVOKED",
  "BREAK_GLASS_LOGIN_SUCCEEDED",
  "BREAK_GLASS_PLATFORM_ACCESS",
  "BREAK_GLASS_TENANT_ENTRY_STARTED",
  "BREAK_GLASS_TENANT_ENTRY_ENDED",
  "BREAK_GLASS_LOGOUT",
  "BREAK_GLASS_IDENTITY_CREATED",
  "BREAK_GLASS_IDENTITY_REPLACED",
  "BREAK_GLASS_IDENTITY_DEACTIVATED",
  "MFA_ENROLLED",
  "MFA_VERIFIED_LOGIN",
  "MFA_CHALLENGE_FAILED",
  "MFA_FACTOR_REMOVED",
  "MFA_FACTOR_RESET_BY_ADMIN",
  "MFA_RESET_RECOVERY",
  "PRIVILEGED_REAUTH_SUCCEEDED",
  "PRIVILEGED_REAUTH_REQUIRED",
  "PRIVILEGED_AAL_DENIED",
  "MFA_ENFORCEMENT_CHANGED",
  "MFA_RECOVERY_REQUESTED",
  "MFA_RECOVERY_APPROVED",
  "MFA_RECOVERY_SECOND_APPROVAL",
  "MFA_RECOVERY_EXECUTED",
  "MFA_TARGET_SESSIONS_REVOKED",
  "MFA_RECOVERY_GRANT_ISSUED",
  "MFA_RECOVERY_GRANT_REDEEMED",
  "MFA_REPLACEMENT_ENROLLED",
  "MFA_RECOVERY_COMPLETED",
  "MFA_RECOVERY_CANCELLED",
  "MFA_RECOVERY_EXPIRED",
  "MFA_RECOVERY_DENIED",
  "MFA_RECOVERY_NOTIFICATION_RECORDED",
  "BREAK_GLASS_SESSION_ENDED",
] as const;

export type PlatformAuditEventType = (typeof PLATFORM_AUDIT_EVENT_TYPES)[number];

const SENSITIVE_META_KEYS = /password|secret|token|totp|service.?role|authorization|cookie/i;

export function sanitisePlatformAuditMetadata(
  metadata: Record<string, unknown> | null | undefined,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(metadata ?? {})) {
    if (SENSITIVE_META_KEYS.test(key)) continue;
    if (typeof value === "string" && SENSITIVE_META_KEYS.test(value)) continue;
    out[key] = value;
  }
  return out;
}
