/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as TenantSlugRouteRouteImport } from './routes/$tenantSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as RafCodeRouteImport } from './routes/raf.$code'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiInterviewStepRouteImport } from './routes/api/interview-step'
import { Route as ApiAvatarTokenRouteImport } from './routes/api/avatar-token'
import { Route as AuthenticatedIntroducerRouteImport } from './routes/_authenticated/introducer'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as TenantSlugWorkspaceRouteImport } from './routes/$tenantSlug/workspace'
import { Route as TenantSlugLoginRouteImport } from './routes/$tenantSlug/login'
import { Route as TenantSlugIntroducerRouteImport } from './routes/$tenantSlug/introducer'
import { Route as TenantSlugHomeRouteImport } from './routes/$tenantSlug/home'
import { Route as TenantSlugDiaryRouteImport } from './routes/$tenantSlug/diary'
import { Route as TenantSlugCompaniesRouteImport } from './routes/$tenantSlug/companies'
import { Route as TenantSlugCasesRouteImport } from './routes/$tenantSlug/cases'
import { Route as TenantSlugBookingRouteImport } from './routes/$tenantSlug/booking'
import { Route as ApiTeamsCallbackRouteImport } from './routes/api/teams/callback'
import { Route as ApiSmsInboundRouteImport } from './routes/api/sms/inbound'
import { Route as ApiIntroducerCalculatorLeadRouteImport } from './routes/api/introducer/calculator-lead'
import { Route as ApiCalculatorMarketRatesRouteImport } from './routes/api/calculator/market-rates'
import { Route as ApiCalculatorEstimateRateRouteImport } from './routes/api/calculator/estimate-rate'
import { Route as ApiAuthRequestPasswordResetRouteImport } from './routes/api/auth/request-password-reset'
import { Route as AuthenticatedTextSessionIdRouteImport } from './routes/_authenticated/text.$sessionId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedInterviewSessionIdRouteImport } from './routes/_authenticated/interview.$sessionId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedChatSessionIdRouteImport } from './routes/_authenticated/chat.$sessionId'
import { Route as TenantSlugTextSessionIdRouteImport } from './routes/$tenantSlug/text.$sessionId'
import { Route as TenantSlugSessionsSessionIdRouteImport } from './routes/$tenantSlug/sessions.$sessionId'
import { Route as TenantSlugRefIntroducerRefRouteImport } from './routes/$tenantSlug/ref.$introducerRef'
import { Route as TenantSlugRafCodeRouteImport } from './routes/$tenantSlug/raf.$code'
import { Route as TenantSlugInterviewSessionIdRouteImport } from './routes/$tenantSlug/interview.$sessionId'
import { Route as TenantSlugCustomersCustomerIdRouteImport } from './routes/$tenantSlug/customers.$customerId'
import { Route as TenantSlugChatSessionIdRouteImport } from './routes/$tenantSlug/chat.$sessionId'
import { Route as TenantSlugBookIntroducerSlugRouteImport } from './routes/$tenantSlug/book.$introducerSlug'
import { Route as ApiTwilioVoiceVoicemailDoneRouteImport } from './routes/api/twilio/voice/voicemail-done'
import { Route as ApiTwilioVoiceSusanPromptRouteImport } from './routes/api/twilio/voice/susan-prompt'
import { Route as ApiTwilioVoiceStatusRouteImport } from './routes/api/twilio/voice/status'
import { Route as ApiTwilioVoiceRecordingRouteImport } from './routes/api/twilio/voice/recording'
import { Route as ApiTwilioVoiceInboundDialDoneRouteImport } from './routes/api/twilio/voice/inbound-dial-done'
import { Route as ApiTwilioVoiceInboundRouteImport } from './routes/api/twilio/voice/inbound'
import { Route as ApiTwilioVoiceClientOutboundRouteImport } from './routes/api/twilio/voice/client-outbound'
import { Route as ApiTwilioVoiceAmdStatusRouteImport } from './routes/api/twilio/voice/amd-status'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugRouteRoute = TenantSlugRouteRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const RafCodeRoute = RafCodeRouteImport.update({
  id: '/raf/$code',
  path: '/raf/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewStepRoute = ApiInterviewStepRouteImport.update({
  id: '/api/interview-step',
  path: '/api/interview-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarTokenRoute = ApiAvatarTokenRouteImport.update({
  id: '/api/avatar-token',
  path: '/api/avatar-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntroducerRoute = AuthenticatedIntroducerRouteImport.update({
  id: '/introducer',
  path: '/introducer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TenantSlugWorkspaceRoute = TenantSlugWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugLoginRoute = TenantSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugIntroducerRoute = TenantSlugIntroducerRouteImport.update({
  id: '/introducer',
  path: '/introducer',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugHomeRoute = TenantSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugDiaryRoute = TenantSlugDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugCompaniesRoute = TenantSlugCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugCasesRoute = TenantSlugCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugBookingRoute = TenantSlugBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const ApiTeamsCallbackRoute = ApiTeamsCallbackRouteImport.update({
  id: '/api/teams/callback',
  path: '/api/teams/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsInboundRoute = ApiSmsInboundRouteImport.update({
  id: '/api/sms/inbound',
  path: '/api/sms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntroducerCalculatorLeadRoute =
  ApiIntroducerCalculatorLeadRouteImport.update({
    id: '/api/introducer/calculator-lead',
    path: '/api/introducer/calculator-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalculatorMarketRatesRoute =
  ApiCalculatorMarketRatesRouteImport.update({
    id: '/api/calculator/market-rates',
    path: '/api/calculator/market-rates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalculatorEstimateRateRoute =
  ApiCalculatorEstimateRateRouteImport.update({
    id: '/api/calculator/estimate-rate',
    path: '/api/calculator/estimate-rate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRequestPasswordResetRoute =
  ApiAuthRequestPasswordResetRouteImport.update({
    id: '/api/auth/request-password-reset',
    path: '/api/auth/request-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTextSessionIdRoute =
  AuthenticatedTextSessionIdRouteImport.update({
    id: '/text/$sessionId',
    path: '/text/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionIdRoute =
  AuthenticatedInterviewSessionIdRouteImport.update({
    id: '/interview/$sessionId',
    path: '/interview/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatSessionIdRoute =
  AuthenticatedChatSessionIdRouteImport.update({
    id: '/chat/$sessionId',
    path: '/chat/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TenantSlugTextSessionIdRoute = TenantSlugTextSessionIdRouteImport.update({
  id: '/text/$sessionId',
  path: '/text/$sessionId',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugSessionsSessionIdRoute =
  TenantSlugSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugRefIntroducerRefRoute =
  TenantSlugRefIntroducerRefRouteImport.update({
    id: '/ref/$introducerRef',
    path: '/ref/$introducerRef',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugRafCodeRoute = TenantSlugRafCodeRouteImport.update({
  id: '/raf/$code',
  path: '/raf/$code',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugInterviewSessionIdRoute =
  TenantSlugInterviewSessionIdRouteImport.update({
    id: '/interview/$sessionId',
    path: '/interview/$sessionId',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugCustomersCustomerIdRoute =
  TenantSlugCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugChatSessionIdRoute = TenantSlugChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugBookIntroducerSlugRoute =
  TenantSlugBookIntroducerSlugRouteImport.update({
    id: '/book/$introducerSlug',
    path: '/book/$introducerSlug',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const ApiTwilioVoiceVoicemailDoneRoute =
  ApiTwilioVoiceVoicemailDoneRouteImport.update({
    id: '/api/twilio/voice/voicemail-done',
    path: '/api/twilio/voice/voicemail-done',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTwilioVoiceSusanPromptRoute =
  ApiTwilioVoiceSusanPromptRouteImport.update({
    id: '/api/twilio/voice/susan-prompt',
    path: '/api/twilio/voice/susan-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTwilioVoiceStatusRoute = ApiTwilioVoiceStatusRouteImport.update({
  id: '/api/twilio/voice/status',
  path: '/api/twilio/voice/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceRecordingRoute = ApiTwilioVoiceRecordingRouteImport.update({
  id: '/api/twilio/voice/recording',
  path: '/api/twilio/voice/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceInboundDialDoneRoute =
  ApiTwilioVoiceInboundDialDoneRouteImport.update({
    id: '/api/twilio/voice/inbound-dial-done',
    path: '/api/twilio/voice/inbound-dial-done',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTwilioVoiceInboundRoute = ApiTwilioVoiceInboundRouteImport.update({
  id: '/api/twilio/voice/inbound',
  path: '/api/twilio/voice/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceClientOutboundRoute =
  ApiTwilioVoiceClientOutboundRouteImport.update({
    id: '/api/twilio/voice/client-outbound',
    path: '/api/twilio/voice/client-outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTwilioVoiceAmdStatusRoute = ApiTwilioVoiceAmdStatusRouteImport.update({
  id: '/api/twilio/voice/amd-status',
  path: '/api/twilio/voice/amd-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/$tenantSlug/booking': typeof TenantSlugBookingRoute
  '/$tenantSlug/cases': typeof TenantSlugCasesRoute
  '/$tenantSlug/companies': typeof TenantSlugCompaniesRoute
  '/$tenantSlug/diary': typeof TenantSlugDiaryRoute
  '/$tenantSlug/home': typeof TenantSlugHomeRoute
  '/$tenantSlug/introducer': typeof TenantSlugIntroducerRoute
  '/$tenantSlug/login': typeof TenantSlugLoginRoute
  '/$tenantSlug/workspace': typeof TenantSlugWorkspaceRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introducer': typeof AuthenticatedIntroducerRoute
  '/api/avatar-token': typeof ApiAvatarTokenRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/reset': typeof AuthResetRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/raf/$code': typeof RafCodeRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/$tenantSlug/book/$introducerSlug': typeof TenantSlugBookIntroducerSlugRoute
  '/$tenantSlug/chat/$sessionId': typeof TenantSlugChatSessionIdRoute
  '/$tenantSlug/customers/$customerId': typeof TenantSlugCustomersCustomerIdRoute
  '/$tenantSlug/interview/$sessionId': typeof TenantSlugInterviewSessionIdRoute
  '/$tenantSlug/raf/$code': typeof TenantSlugRafCodeRoute
  '/$tenantSlug/ref/$introducerRef': typeof TenantSlugRefIntroducerRefRoute
  '/$tenantSlug/sessions/$sessionId': typeof TenantSlugSessionsSessionIdRoute
  '/$tenantSlug/text/$sessionId': typeof TenantSlugTextSessionIdRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/calculator/estimate-rate': typeof ApiCalculatorEstimateRateRoute
  '/api/calculator/market-rates': typeof ApiCalculatorMarketRatesRoute
  '/api/introducer/calculator-lead': typeof ApiIntroducerCalculatorLeadRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/teams/callback': typeof ApiTeamsCallbackRoute
  '/api/twilio/voice/amd-status': typeof ApiTwilioVoiceAmdStatusRoute
  '/api/twilio/voice/client-outbound': typeof ApiTwilioVoiceClientOutboundRoute
  '/api/twilio/voice/inbound': typeof ApiTwilioVoiceInboundRoute
  '/api/twilio/voice/inbound-dial-done': typeof ApiTwilioVoiceInboundDialDoneRoute
  '/api/twilio/voice/recording': typeof ApiTwilioVoiceRecordingRoute
  '/api/twilio/voice/status': typeof ApiTwilioVoiceStatusRoute
  '/api/twilio/voice/susan-prompt': typeof ApiTwilioVoiceSusanPromptRoute
  '/api/twilio/voice/voicemail-done': typeof ApiTwilioVoiceVoicemailDoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/$tenantSlug/booking': typeof TenantSlugBookingRoute
  '/$tenantSlug/cases': typeof TenantSlugCasesRoute
  '/$tenantSlug/companies': typeof TenantSlugCompaniesRoute
  '/$tenantSlug/diary': typeof TenantSlugDiaryRoute
  '/$tenantSlug/home': typeof TenantSlugHomeRoute
  '/$tenantSlug/introducer': typeof TenantSlugIntroducerRoute
  '/$tenantSlug/login': typeof TenantSlugLoginRoute
  '/$tenantSlug/workspace': typeof TenantSlugWorkspaceRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introducer': typeof AuthenticatedIntroducerRoute
  '/api/avatar-token': typeof ApiAvatarTokenRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/reset': typeof AuthResetRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/raf/$code': typeof RafCodeRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/$tenantSlug/book/$introducerSlug': typeof TenantSlugBookIntroducerSlugRoute
  '/$tenantSlug/chat/$sessionId': typeof TenantSlugChatSessionIdRoute
  '/$tenantSlug/customers/$customerId': typeof TenantSlugCustomersCustomerIdRoute
  '/$tenantSlug/interview/$sessionId': typeof TenantSlugInterviewSessionIdRoute
  '/$tenantSlug/raf/$code': typeof TenantSlugRafCodeRoute
  '/$tenantSlug/ref/$introducerRef': typeof TenantSlugRefIntroducerRefRoute
  '/$tenantSlug/sessions/$sessionId': typeof TenantSlugSessionsSessionIdRoute
  '/$tenantSlug/text/$sessionId': typeof TenantSlugTextSessionIdRoute
  '/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/calculator/estimate-rate': typeof ApiCalculatorEstimateRateRoute
  '/api/calculator/market-rates': typeof ApiCalculatorMarketRatesRoute
  '/api/introducer/calculator-lead': typeof ApiIntroducerCalculatorLeadRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/teams/callback': typeof ApiTeamsCallbackRoute
  '/api/twilio/voice/amd-status': typeof ApiTwilioVoiceAmdStatusRoute
  '/api/twilio/voice/client-outbound': typeof ApiTwilioVoiceClientOutboundRoute
  '/api/twilio/voice/inbound': typeof ApiTwilioVoiceInboundRoute
  '/api/twilio/voice/inbound-dial-done': typeof ApiTwilioVoiceInboundDialDoneRoute
  '/api/twilio/voice/recording': typeof ApiTwilioVoiceRecordingRoute
  '/api/twilio/voice/status': typeof ApiTwilioVoiceStatusRoute
  '/api/twilio/voice/susan-prompt': typeof ApiTwilioVoiceSusanPromptRoute
  '/api/twilio/voice/voicemail-done': typeof ApiTwilioVoiceVoicemailDoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/$tenantSlug/booking': typeof TenantSlugBookingRoute
  '/$tenantSlug/cases': typeof TenantSlugCasesRoute
  '/$tenantSlug/companies': typeof TenantSlugCompaniesRoute
  '/$tenantSlug/diary': typeof TenantSlugDiaryRoute
  '/$tenantSlug/home': typeof TenantSlugHomeRoute
  '/$tenantSlug/introducer': typeof TenantSlugIntroducerRoute
  '/$tenantSlug/login': typeof TenantSlugLoginRoute
  '/$tenantSlug/workspace': typeof TenantSlugWorkspaceRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/introducer': typeof AuthenticatedIntroducerRoute
  '/api/avatar-token': typeof ApiAvatarTokenRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/reset': typeof AuthResetRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/raf/$code': typeof RafCodeRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/$tenantSlug/book/$introducerSlug': typeof TenantSlugBookIntroducerSlugRoute
  '/$tenantSlug/chat/$sessionId': typeof TenantSlugChatSessionIdRoute
  '/$tenantSlug/customers/$customerId': typeof TenantSlugCustomersCustomerIdRoute
  '/$tenantSlug/interview/$sessionId': typeof TenantSlugInterviewSessionIdRoute
  '/$tenantSlug/raf/$code': typeof TenantSlugRafCodeRoute
  '/$tenantSlug/ref/$introducerRef': typeof TenantSlugRefIntroducerRefRoute
  '/$tenantSlug/sessions/$sessionId': typeof TenantSlugSessionsSessionIdRoute
  '/$tenantSlug/text/$sessionId': typeof TenantSlugTextSessionIdRoute
  '/_authenticated/chat/$sessionId': typeof AuthenticatedChatSessionIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/calculator/estimate-rate': typeof ApiCalculatorEstimateRateRoute
  '/api/calculator/market-rates': typeof ApiCalculatorMarketRatesRoute
  '/api/introducer/calculator-lead': typeof ApiIntroducerCalculatorLeadRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/teams/callback': typeof ApiTeamsCallbackRoute
  '/api/twilio/voice/amd-status': typeof ApiTwilioVoiceAmdStatusRoute
  '/api/twilio/voice/client-outbound': typeof ApiTwilioVoiceClientOutboundRoute
  '/api/twilio/voice/inbound': typeof ApiTwilioVoiceInboundRoute
  '/api/twilio/voice/inbound-dial-done': typeof ApiTwilioVoiceInboundDialDoneRoute
  '/api/twilio/voice/recording': typeof ApiTwilioVoiceRecordingRoute
  '/api/twilio/voice/status': typeof ApiTwilioVoiceStatusRoute
  '/api/twilio/voice/susan-prompt': typeof ApiTwilioVoiceSusanPromptRoute
  '/api/twilio/voice/voicemail-done': typeof ApiTwilioVoiceVoicemailDoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantSlug'
    | '/auth'
    | '/register'
    | '/$tenantSlug/booking'
    | '/$tenantSlug/cases'
    | '/$tenantSlug/companies'
    | '/$tenantSlug/diary'
    | '/$tenantSlug/home'
    | '/$tenantSlug/introducer'
    | '/$tenantSlug/login'
    | '/$tenantSlug/workspace'
    | '/booking'
    | '/cases'
    | '/companies'
    | '/diary'
    | '/home'
    | '/introducer'
    | '/api/avatar-token'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/auth/reset'
    | '/book/$slug'
    | '/go/$slug'
    | '/raf/$code'
    | '/$tenantSlug/'
    | '/$tenantSlug/book/$introducerSlug'
    | '/$tenantSlug/chat/$sessionId'
    | '/$tenantSlug/customers/$customerId'
    | '/$tenantSlug/interview/$sessionId'
    | '/$tenantSlug/raf/$code'
    | '/$tenantSlug/ref/$introducerRef'
    | '/$tenantSlug/sessions/$sessionId'
    | '/$tenantSlug/text/$sessionId'
    | '/chat/$sessionId'
    | '/customers/$customerId'
    | '/interview/$sessionId'
    | '/sessions/$sessionId'
    | '/text/$sessionId'
    | '/api/auth/request-password-reset'
    | '/api/calculator/estimate-rate'
    | '/api/calculator/market-rates'
    | '/api/introducer/calculator-lead'
    | '/api/sms/inbound'
    | '/api/teams/callback'
    | '/api/twilio/voice/amd-status'
    | '/api/twilio/voice/client-outbound'
    | '/api/twilio/voice/inbound'
    | '/api/twilio/voice/inbound-dial-done'
    | '/api/twilio/voice/recording'
    | '/api/twilio/voice/status'
    | '/api/twilio/voice/susan-prompt'
    | '/api/twilio/voice/voicemail-done'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/$tenantSlug/booking'
    | '/$tenantSlug/cases'
    | '/$tenantSlug/companies'
    | '/$tenantSlug/diary'
    | '/$tenantSlug/home'
    | '/$tenantSlug/introducer'
    | '/$tenantSlug/login'
    | '/$tenantSlug/workspace'
    | '/booking'
    | '/cases'
    | '/companies'
    | '/diary'
    | '/home'
    | '/introducer'
    | '/api/avatar-token'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/auth/reset'
    | '/book/$slug'
    | '/go/$slug'
    | '/raf/$code'
    | '/$tenantSlug'
    | '/$tenantSlug/book/$introducerSlug'
    | '/$tenantSlug/chat/$sessionId'
    | '/$tenantSlug/customers/$customerId'
    | '/$tenantSlug/interview/$sessionId'
    | '/$tenantSlug/raf/$code'
    | '/$tenantSlug/ref/$introducerRef'
    | '/$tenantSlug/sessions/$sessionId'
    | '/$tenantSlug/text/$sessionId'
    | '/chat/$sessionId'
    | '/customers/$customerId'
    | '/interview/$sessionId'
    | '/sessions/$sessionId'
    | '/text/$sessionId'
    | '/api/auth/request-password-reset'
    | '/api/calculator/estimate-rate'
    | '/api/calculator/market-rates'
    | '/api/introducer/calculator-lead'
    | '/api/sms/inbound'
    | '/api/teams/callback'
    | '/api/twilio/voice/amd-status'
    | '/api/twilio/voice/client-outbound'
    | '/api/twilio/voice/inbound'
    | '/api/twilio/voice/inbound-dial-done'
    | '/api/twilio/voice/recording'
    | '/api/twilio/voice/status'
    | '/api/twilio/voice/susan-prompt'
    | '/api/twilio/voice/voicemail-done'
  id:
    | '__root__'
    | '/'
    | '/$tenantSlug'
    | '/_authenticated'
    | '/auth'
    | '/register'
    | '/$tenantSlug/booking'
    | '/$tenantSlug/cases'
    | '/$tenantSlug/companies'
    | '/$tenantSlug/diary'
    | '/$tenantSlug/home'
    | '/$tenantSlug/introducer'
    | '/$tenantSlug/login'
    | '/$tenantSlug/workspace'
    | '/_authenticated/booking'
    | '/_authenticated/cases'
    | '/_authenticated/companies'
    | '/_authenticated/diary'
    | '/_authenticated/home'
    | '/_authenticated/introducer'
    | '/api/avatar-token'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/auth/reset'
    | '/book/$slug'
    | '/go/$slug'
    | '/raf/$code'
    | '/$tenantSlug/'
    | '/$tenantSlug/book/$introducerSlug'
    | '/$tenantSlug/chat/$sessionId'
    | '/$tenantSlug/customers/$customerId'
    | '/$tenantSlug/interview/$sessionId'
    | '/$tenantSlug/raf/$code'
    | '/$tenantSlug/ref/$introducerRef'
    | '/$tenantSlug/sessions/$sessionId'
    | '/$tenantSlug/text/$sessionId'
    | '/_authenticated/chat/$sessionId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/interview/$sessionId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/text/$sessionId'
    | '/api/auth/request-password-reset'
    | '/api/calculator/estimate-rate'
    | '/api/calculator/market-rates'
    | '/api/introducer/calculator-lead'
    | '/api/sms/inbound'
    | '/api/teams/callback'
    | '/api/twilio/voice/amd-status'
    | '/api/twilio/voice/client-outbound'
    | '/api/twilio/voice/inbound'
    | '/api/twilio/voice/inbound-dial-done'
    | '/api/twilio/voice/recording'
    | '/api/twilio/voice/status'
    | '/api/twilio/voice/susan-prompt'
    | '/api/twilio/voice/voicemail-done'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantSlugRouteRoute: typeof TenantSlugRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ApiAvatarTokenRoute: typeof ApiAvatarTokenRoute
  ApiInterviewStepRoute: typeof ApiInterviewStepRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  BookSlugRoute: typeof BookSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  RafCodeRoute: typeof RafCodeRoute
  ApiAuthRequestPasswordResetRoute: typeof ApiAuthRequestPasswordResetRoute
  ApiCalculatorEstimateRateRoute: typeof ApiCalculatorEstimateRateRoute
  ApiCalculatorMarketRatesRoute: typeof ApiCalculatorMarketRatesRoute
  ApiIntroducerCalculatorLeadRoute: typeof ApiIntroducerCalculatorLeadRoute
  ApiSmsInboundRoute: typeof ApiSmsInboundRoute
  ApiTeamsCallbackRoute: typeof ApiTeamsCallbackRoute
  ApiTwilioVoiceAmdStatusRoute: typeof ApiTwilioVoiceAmdStatusRoute
  ApiTwilioVoiceClientOutboundRoute: typeof ApiTwilioVoiceClientOutboundRoute
  ApiTwilioVoiceInboundRoute: typeof ApiTwilioVoiceInboundRoute
  ApiTwilioVoiceInboundDialDoneRoute: typeof ApiTwilioVoiceInboundDialDoneRoute
  ApiTwilioVoiceRecordingRoute: typeof ApiTwilioVoiceRecordingRoute
  ApiTwilioVoiceStatusRoute: typeof ApiTwilioVoiceStatusRoute
  ApiTwilioVoiceSusanPromptRoute: typeof ApiTwilioVoiceSusanPromptRoute
  ApiTwilioVoiceVoicemailDoneRoute: typeof ApiTwilioVoiceVoicemailDoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/raf/$code': {
      id: '/raf/$code'
      path: '/raf/$code'
      fullPath: '/raf/$code'
      preLoaderRoute: typeof RafCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-step': {
      id: '/api/interview-step'
      path: '/api/interview-step'
      fullPath: '/api/interview-step'
      preLoaderRoute: typeof ApiInterviewStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar-token': {
      id: '/api/avatar-token'
      path: '/api/avatar-token'
      fullPath: '/api/avatar-token'
      preLoaderRoute: typeof ApiAvatarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/introducer': {
      id: '/_authenticated/introducer'
      path: '/introducer'
      fullPath: '/introducer'
      preLoaderRoute: typeof AuthenticatedIntroducerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$tenantSlug/workspace': {
      id: '/$tenantSlug/workspace'
      path: '/workspace'
      fullPath: '/$tenantSlug/workspace'
      preLoaderRoute: typeof TenantSlugWorkspaceRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/login': {
      id: '/$tenantSlug/login'
      path: '/login'
      fullPath: '/$tenantSlug/login'
      preLoaderRoute: typeof TenantSlugLoginRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/introducer': {
      id: '/$tenantSlug/introducer'
      path: '/introducer'
      fullPath: '/$tenantSlug/introducer'
      preLoaderRoute: typeof TenantSlugIntroducerRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/home': {
      id: '/$tenantSlug/home'
      path: '/home'
      fullPath: '/$tenantSlug/home'
      preLoaderRoute: typeof TenantSlugHomeRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/diary': {
      id: '/$tenantSlug/diary'
      path: '/diary'
      fullPath: '/$tenantSlug/diary'
      preLoaderRoute: typeof TenantSlugDiaryRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/companies': {
      id: '/$tenantSlug/companies'
      path: '/companies'
      fullPath: '/$tenantSlug/companies'
      preLoaderRoute: typeof TenantSlugCompaniesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/cases': {
      id: '/$tenantSlug/cases'
      path: '/cases'
      fullPath: '/$tenantSlug/cases'
      preLoaderRoute: typeof TenantSlugCasesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/booking': {
      id: '/$tenantSlug/booking'
      path: '/booking'
      fullPath: '/$tenantSlug/booking'
      preLoaderRoute: typeof TenantSlugBookingRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/api/teams/callback': {
      id: '/api/teams/callback'
      path: '/api/teams/callback'
      fullPath: '/api/teams/callback'
      preLoaderRoute: typeof ApiTeamsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/inbound': {
      id: '/api/sms/inbound'
      path: '/api/sms/inbound'
      fullPath: '/api/sms/inbound'
      preLoaderRoute: typeof ApiSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/introducer/calculator-lead': {
      id: '/api/introducer/calculator-lead'
      path: '/api/introducer/calculator-lead'
      fullPath: '/api/introducer/calculator-lead'
      preLoaderRoute: typeof ApiIntroducerCalculatorLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calculator/market-rates': {
      id: '/api/calculator/market-rates'
      path: '/api/calculator/market-rates'
      fullPath: '/api/calculator/market-rates'
      preLoaderRoute: typeof ApiCalculatorMarketRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calculator/estimate-rate': {
      id: '/api/calculator/estimate-rate'
      path: '/api/calculator/estimate-rate'
      fullPath: '/api/calculator/estimate-rate'
      preLoaderRoute: typeof ApiCalculatorEstimateRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-password-reset': {
      id: '/api/auth/request-password-reset'
      path: '/api/auth/request-password-reset'
      fullPath: '/api/auth/request-password-reset'
      preLoaderRoute: typeof ApiAuthRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/text/$sessionId': {
      id: '/_authenticated/text/$sessionId'
      path: '/text/$sessionId'
      fullPath: '/text/$sessionId'
      preLoaderRoute: typeof AuthenticatedTextSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$sessionId': {
      id: '/_authenticated/interview/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$sessionId': {
      id: '/_authenticated/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthenticatedChatSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$tenantSlug/text/$sessionId': {
      id: '/$tenantSlug/text/$sessionId'
      path: '/text/$sessionId'
      fullPath: '/$tenantSlug/text/$sessionId'
      preLoaderRoute: typeof TenantSlugTextSessionIdRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/sessions/$sessionId': {
      id: '/$tenantSlug/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$tenantSlug/sessions/$sessionId'
      preLoaderRoute: typeof TenantSlugSessionsSessionIdRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/ref/$introducerRef': {
      id: '/$tenantSlug/ref/$introducerRef'
      path: '/ref/$introducerRef'
      fullPath: '/$tenantSlug/ref/$introducerRef'
      preLoaderRoute: typeof TenantSlugRefIntroducerRefRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/raf/$code': {
      id: '/$tenantSlug/raf/$code'
      path: '/raf/$code'
      fullPath: '/$tenantSlug/raf/$code'
      preLoaderRoute: typeof TenantSlugRafCodeRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/interview/$sessionId': {
      id: '/$tenantSlug/interview/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/$tenantSlug/interview/$sessionId'
      preLoaderRoute: typeof TenantSlugInterviewSessionIdRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/customers/$customerId': {
      id: '/$tenantSlug/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$tenantSlug/customers/$customerId'
      preLoaderRoute: typeof TenantSlugCustomersCustomerIdRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/chat/$sessionId': {
      id: '/$tenantSlug/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/$tenantSlug/chat/$sessionId'
      preLoaderRoute: typeof TenantSlugChatSessionIdRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/book/$introducerSlug': {
      id: '/$tenantSlug/book/$introducerSlug'
      path: '/book/$introducerSlug'
      fullPath: '/$tenantSlug/book/$introducerSlug'
      preLoaderRoute: typeof TenantSlugBookIntroducerSlugRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/api/twilio/voice/voicemail-done': {
      id: '/api/twilio/voice/voicemail-done'
      path: '/api/twilio/voice/voicemail-done'
      fullPath: '/api/twilio/voice/voicemail-done'
      preLoaderRoute: typeof ApiTwilioVoiceVoicemailDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/susan-prompt': {
      id: '/api/twilio/voice/susan-prompt'
      path: '/api/twilio/voice/susan-prompt'
      fullPath: '/api/twilio/voice/susan-prompt'
      preLoaderRoute: typeof ApiTwilioVoiceSusanPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/status': {
      id: '/api/twilio/voice/status'
      path: '/api/twilio/voice/status'
      fullPath: '/api/twilio/voice/status'
      preLoaderRoute: typeof ApiTwilioVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/recording': {
      id: '/api/twilio/voice/recording'
      path: '/api/twilio/voice/recording'
      fullPath: '/api/twilio/voice/recording'
      preLoaderRoute: typeof ApiTwilioVoiceRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/inbound-dial-done': {
      id: '/api/twilio/voice/inbound-dial-done'
      path: '/api/twilio/voice/inbound-dial-done'
      fullPath: '/api/twilio/voice/inbound-dial-done'
      preLoaderRoute: typeof ApiTwilioVoiceInboundDialDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/inbound': {
      id: '/api/twilio/voice/inbound'
      path: '/api/twilio/voice/inbound'
      fullPath: '/api/twilio/voice/inbound'
      preLoaderRoute: typeof ApiTwilioVoiceInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/client-outbound': {
      id: '/api/twilio/voice/client-outbound'
      path: '/api/twilio/voice/client-outbound'
      fullPath: '/api/twilio/voice/client-outbound'
      preLoaderRoute: typeof ApiTwilioVoiceClientOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice/amd-status': {
      id: '/api/twilio/voice/amd-status'
      path: '/api/twilio/voice/amd-status'
      fullPath: '/api/twilio/voice/amd-status'
      preLoaderRoute: typeof ApiTwilioVoiceAmdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TenantSlugRouteRouteChildren {
  TenantSlugBookingRoute: typeof TenantSlugBookingRoute
  TenantSlugCasesRoute: typeof TenantSlugCasesRoute
  TenantSlugCompaniesRoute: typeof TenantSlugCompaniesRoute
  TenantSlugDiaryRoute: typeof TenantSlugDiaryRoute
  TenantSlugHomeRoute: typeof TenantSlugHomeRoute
  TenantSlugIntroducerRoute: typeof TenantSlugIntroducerRoute
  TenantSlugLoginRoute: typeof TenantSlugLoginRoute
  TenantSlugWorkspaceRoute: typeof TenantSlugWorkspaceRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  TenantSlugBookIntroducerSlugRoute: typeof TenantSlugBookIntroducerSlugRoute
  TenantSlugChatSessionIdRoute: typeof TenantSlugChatSessionIdRoute
  TenantSlugCustomersCustomerIdRoute: typeof TenantSlugCustomersCustomerIdRoute
  TenantSlugInterviewSessionIdRoute: typeof TenantSlugInterviewSessionIdRoute
  TenantSlugRafCodeRoute: typeof TenantSlugRafCodeRoute
  TenantSlugRefIntroducerRefRoute: typeof TenantSlugRefIntroducerRefRoute
  TenantSlugSessionsSessionIdRoute: typeof TenantSlugSessionsSessionIdRoute
  TenantSlugTextSessionIdRoute: typeof TenantSlugTextSessionIdRoute
}

const TenantSlugRouteRouteChildren: TenantSlugRouteRouteChildren = {
  TenantSlugBookingRoute: TenantSlugBookingRoute,
  TenantSlugCasesRoute: TenantSlugCasesRoute,
  TenantSlugCompaniesRoute: TenantSlugCompaniesRoute,
  TenantSlugDiaryRoute: TenantSlugDiaryRoute,
  TenantSlugHomeRoute: TenantSlugHomeRoute,
  TenantSlugIntroducerRoute: TenantSlugIntroducerRoute,
  TenantSlugLoginRoute: TenantSlugLoginRoute,
  TenantSlugWorkspaceRoute: TenantSlugWorkspaceRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  TenantSlugBookIntroducerSlugRoute: TenantSlugBookIntroducerSlugRoute,
  TenantSlugChatSessionIdRoute: TenantSlugChatSessionIdRoute,
  TenantSlugCustomersCustomerIdRoute: TenantSlugCustomersCustomerIdRoute,
  TenantSlugInterviewSessionIdRoute: TenantSlugInterviewSessionIdRoute,
  TenantSlugRafCodeRoute: TenantSlugRafCodeRoute,
  TenantSlugRefIntroducerRefRoute: TenantSlugRefIntroducerRefRoute,
  TenantSlugSessionsSessionIdRoute: TenantSlugSessionsSessionIdRoute,
  TenantSlugTextSessionIdRoute: TenantSlugTextSessionIdRoute,
}

const TenantSlugRouteRouteWithChildren = TenantSlugRouteRoute._addFileChildren(
  TenantSlugRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntroducerRoute: typeof AuthenticatedIntroducerRoute
  AuthenticatedChatSessionIdRoute: typeof AuthenticatedChatSessionIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedInterviewSessionIdRoute: typeof AuthenticatedInterviewSessionIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedTextSessionIdRoute: typeof AuthenticatedTextSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntroducerRoute: AuthenticatedIntroducerRoute,
  AuthenticatedChatSessionIdRoute: AuthenticatedChatSessionIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedInterviewSessionIdRoute: AuthenticatedInterviewSessionIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedTextSessionIdRoute: AuthenticatedTextSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantSlugRouteRoute: TenantSlugRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ApiAvatarTokenRoute: ApiAvatarTokenRoute,
  ApiInterviewStepRoute: ApiInterviewStepRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  BookSlugRoute: BookSlugRoute,
  GoSlugRoute: GoSlugRoute,
  RafCodeRoute: RafCodeRoute,
  ApiAuthRequestPasswordResetRoute: ApiAuthRequestPasswordResetRoute,
  ApiCalculatorEstimateRateRoute: ApiCalculatorEstimateRateRoute,
  ApiCalculatorMarketRatesRoute: ApiCalculatorMarketRatesRoute,
  ApiIntroducerCalculatorLeadRoute: ApiIntroducerCalculatorLeadRoute,
  ApiSmsInboundRoute: ApiSmsInboundRoute,
  ApiTeamsCallbackRoute: ApiTeamsCallbackRoute,
  ApiTwilioVoiceAmdStatusRoute: ApiTwilioVoiceAmdStatusRoute,
  ApiTwilioVoiceClientOutboundRoute: ApiTwilioVoiceClientOutboundRoute,
  ApiTwilioVoiceInboundRoute: ApiTwilioVoiceInboundRoute,
  ApiTwilioVoiceInboundDialDoneRoute: ApiTwilioVoiceInboundDialDoneRoute,
  ApiTwilioVoiceRecordingRoute: ApiTwilioVoiceRecordingRoute,
  ApiTwilioVoiceStatusRoute: ApiTwilioVoiceStatusRoute,
  ApiTwilioVoiceSusanPromptRoute: ApiTwilioVoiceSusanPromptRoute,
  ApiTwilioVoiceVoicemailDoneRoute: ApiTwilioVoiceVoicemailDoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
