/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiInterviewStepRouteImport } from './routes/api/interview-step'
import { Route as AuthenticatedIntroducerRouteImport } from './routes/_authenticated/introducer'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as ApiSmsInboundRouteImport } from './routes/api/sms/inbound'
import { Route as AuthenticatedTextSessionIdRouteImport } from './routes/_authenticated/text.$sessionId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedInterviewSessionIdRouteImport } from './routes/_authenticated/interview.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewStepRoute = ApiInterviewStepRouteImport.update({
  id: '/api/interview-step',
  path: '/api/interview-step',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntroducerRoute = AuthenticatedIntroducerRouteImport.update({
  id: '/introducer',
  path: '/introducer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSmsInboundRoute = ApiSmsInboundRouteImport.update({
  id: '/api/sms/inbound',
  path: '/api/sms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextSessionIdRoute =
  AuthenticatedTextSessionIdRouteImport.update({
    id: '/text/$sessionId',
    path: '/text/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionIdRoute =
  AuthenticatedInterviewSessionIdRouteImport.update({
    id: '/interview/$sessionId',
    path: '/interview/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introducer': typeof AuthenticatedIntroducerRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/introducer': typeof AuthenticatedIntroducerRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/introducer': typeof AuthenticatedIntroducerRoute
  '/api/interview-step': typeof ApiInterviewStepRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/book/$slug': typeof BookSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/_authenticated/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/text/$sessionId': typeof AuthenticatedTextSessionIdRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/diary'
    | '/home'
    | '/introducer'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/book/$slug'
    | '/go/$slug'
    | '/interview/$sessionId'
    | '/sessions/$sessionId'
    | '/text/$sessionId'
    | '/api/sms/inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/diary'
    | '/home'
    | '/introducer'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/book/$slug'
    | '/go/$slug'
    | '/interview/$sessionId'
    | '/sessions/$sessionId'
    | '/text/$sessionId'
    | '/api/sms/inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/booking'
    | '/_authenticated/diary'
    | '/_authenticated/home'
    | '/_authenticated/introducer'
    | '/api/interview-step'
    | '/api/stt'
    | '/api/tts'
    | '/book/$slug'
    | '/go/$slug'
    | '/_authenticated/interview/$sessionId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/text/$sessionId'
    | '/api/sms/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiInterviewStepRoute: typeof ApiInterviewStepRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  BookSlugRoute: typeof BookSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  ApiSmsInboundRoute: typeof ApiSmsInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-step': {
      id: '/api/interview-step'
      path: '/api/interview-step'
      fullPath: '/api/interview-step'
      preLoaderRoute: typeof ApiInterviewStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/introducer': {
      id: '/_authenticated/introducer'
      path: '/introducer'
      fullPath: '/introducer'
      preLoaderRoute: typeof AuthenticatedIntroducerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sms/inbound': {
      id: '/api/sms/inbound'
      path: '/api/sms/inbound'
      fullPath: '/api/sms/inbound'
      preLoaderRoute: typeof ApiSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/text/$sessionId': {
      id: '/_authenticated/text/$sessionId'
      path: '/text/$sessionId'
      fullPath: '/text/$sessionId'
      preLoaderRoute: typeof AuthenticatedTextSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$sessionId': {
      id: '/_authenticated/interview/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntroducerRoute: typeof AuthenticatedIntroducerRoute
  AuthenticatedInterviewSessionIdRoute: typeof AuthenticatedInterviewSessionIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedTextSessionIdRoute: typeof AuthenticatedTextSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntroducerRoute: AuthenticatedIntroducerRoute,
  AuthenticatedInterviewSessionIdRoute: AuthenticatedInterviewSessionIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedTextSessionIdRoute: AuthenticatedTextSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiInterviewStepRoute: ApiInterviewStepRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  BookSlugRoute: BookSlugRoute,
  GoSlugRoute: GoSlugRoute,
  ApiSmsInboundRoute: ApiSmsInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
