-- G7F-3C3: privileged MFA recovery and factor replacement (Option D).
--
-- Recovery suspends platform authority; it never removes platform_roles, tenant_memberships or
-- grants. While public.platform_mfa_recovery_locks holds a row for a user, is_super_owner() and
-- is_super_admin() return false for that user, so every RLS policy, SECURITY DEFINER helper and
-- server authority check that derives from them denies — independent of PRIVILEGED_MFA_MODE and of
-- any access token issued before the recovery.
--
-- All state changes go through service_role-only SECURITY DEFINER RPCs that lock the request row
-- (SELECT ... FOR UPDATE) plus a per-target advisory lock (execution also takes a global lock) and
-- re-check every authority and invariant inside the lock. The tables are write-guarded so even a
-- service_role session cannot mutate them directly.
--
-- Auth schema assumptions (verified on staging before this migration, pinned by
-- scripts/g7f3c3-mfa-recovery-verify.sql):
--   auth.mfa_challenges.factor_id -> auth.mfa_factors ON DELETE CASCADE
--   auth.mfa_recovery_code_sets.mfa_factor_id -> auth.mfa_factors ON DELETE CASCADE
--   auth.refresh_tokens.session_id / auth.mfa_amr_claims.session_id -> auth.sessions ON DELETE CASCADE
--   auth.refresh_tokens.user_id is varchar; auth.sessions has aal, factor_id, not_after, created_at.
--
-- The one-time recovery grant is generated by the application server; only its SHA-256 hex digest
-- reaches the database, and that digest is not readable through any grant.

-- ---------------------------------------------------------------------------------------------
-- 1. Break-glass session end reason: add mfa_recovery (D1 time/idle/binding invariants unchanged)
-- ---------------------------------------------------------------------------------------------
ALTER TABLE public.platform_break_glass_sessions
  DROP CONSTRAINT IF EXISTS platform_break_glass_sessions_end_reason_chk;
ALTER TABLE public.platform_break_glass_sessions
  ADD CONSTRAINT platform_break_glass_sessions_end_reason_chk CHECK (
    end_reason IS NULL OR end_reason = ANY (ARRAY[
      'logout'::text, 'absolute_expired'::text, 'idle_expired'::text,
      'classification_removed'::text, 'role_removed'::text, 'replaced'::text,
      'mfa_recovery'::text
    ])
  );

-- ---------------------------------------------------------------------------------------------
-- 2. Recovery requests
-- ---------------------------------------------------------------------------------------------
CREATE TABLE public.platform_mfa_recovery_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_kind text NOT NULL,
  target_factor_id uuid,
  requested_by uuid NOT NULL,
  requested_session_id uuid NOT NULL,
  approved_by uuid NOT NULL,
  approved_session_id uuid NOT NULL,
  approved_at timestamptz NOT NULL,
  second_approved_by uuid,
  second_session_id uuid,
  second_approved_at timestamptz,
  executed_by uuid,
  executed_session_id uuid,
  cancelled_by uuid,
  reason text NOT NULL,
  terminal_reason text,
  cooling_off_until timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'requested',
  created_at timestamptz NOT NULL DEFAULT now(),
  executed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  expires_at timestamptz NOT NULL,
  grant_hash text,
  grant_issued_at timestamptz,
  grant_expires_at timestamptz,
  grant_redeemed_at timestamptz,
  grant_failed_attempts integer NOT NULL DEFAULT 0,
  redeemed_session_id uuid,
  replacement_factor_id uuid,
  evidence_type text,
  evidence_ref text,
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT platform_mfa_recovery_target_kind_chk
    CHECK (target_kind IN ('normal_so', 'super_admin', 'break_glass')),
  CONSTRAINT platform_mfa_recovery_status_chk
    CHECK (status IN ('requested', 'approved', 'executed_awaiting_enrolment', 'completed',
                      'cancelled', 'expired', 'denied', 'failed')),
  CONSTRAINT platform_mfa_recovery_reason_chk
    CHECK (length(btrim(reason)) BETWEEN 10 AND 500),
  CONSTRAINT platform_mfa_recovery_terminal_reason_chk
    CHECK (terminal_reason IS NULL OR length(terminal_reason) <= 120),
  -- The initiator's request is the first approval.
  CONSTRAINT platform_mfa_recovery_first_approval_chk
    CHECK (approved_by = requested_by AND approved_session_id = requested_session_id),
  CONSTRAINT platform_mfa_recovery_requester_not_target_chk
    CHECK (requested_by <> target_user_id AND approved_by <> target_user_id),
  CONSTRAINT platform_mfa_recovery_second_approval_chk
    CHECK (
      (second_approved_by IS NULL AND second_session_id IS NULL AND second_approved_at IS NULL)
      OR (second_approved_by IS NOT NULL AND second_session_id IS NOT NULL AND second_approved_at IS NOT NULL
          AND second_approved_by <> target_user_id
          AND second_approved_by <> approved_by
          AND second_approved_by <> requested_by
          AND second_session_id <> approved_session_id)
    ),
  CONSTRAINT platform_mfa_recovery_executor_chk
    CHECK (executed_by IS NULL OR (executed_by <> target_user_id AND executed_session_id IS NOT NULL)),
  CONSTRAINT platform_mfa_recovery_cooling_off_floor_chk
    CHECK (target_kind = 'super_admin' OR cooling_off_until >= created_at + interval '15 minutes'),
  CONSTRAINT platform_mfa_recovery_grant_hash_chk
    CHECK (grant_hash IS NULL OR grant_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT platform_mfa_recovery_grant_fields_chk
    CHECK ((grant_hash IS NULL) = (grant_issued_at IS NULL) AND (grant_hash IS NULL) = (grant_expires_at IS NULL)),
  CONSTRAINT platform_mfa_recovery_grant_expiry_chk
    CHECK (grant_expires_at IS NULL OR grant_expires_at <= grant_issued_at + interval '30 minutes'),
  CONSTRAINT platform_mfa_recovery_redeemed_pair_chk
    CHECK ((grant_redeemed_at IS NULL) = (redeemed_session_id IS NULL)),
  CONSTRAINT platform_mfa_recovery_grant_attempts_chk
    CHECK (grant_failed_attempts >= 0),
  CONSTRAINT platform_mfa_recovery_execution_fields_chk
    CHECK (
      (status IN ('requested', 'approved', 'cancelled', 'denied') AND executed_at IS NULL AND grant_hash IS NULL)
      OR (status IN ('executed_awaiting_enrolment', 'completed', 'failed')
          AND executed_at IS NOT NULL AND executed_by IS NOT NULL AND grant_hash IS NOT NULL)
      OR status = 'expired'
    ),
  CONSTRAINT platform_mfa_recovery_enrolment_window_chk
    CHECK (executed_at IS NULL OR expires_at <= executed_at + interval '24 hours'),
  CONSTRAINT platform_mfa_recovery_completed_chk
    CHECK (status <> 'completed'
           OR (completed_at IS NOT NULL AND replacement_factor_id IS NOT NULL AND grant_redeemed_at IS NOT NULL)),
  CONSTRAINT platform_mfa_recovery_cancelled_chk
    CHECK (status <> 'cancelled' OR (cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL)),
  -- Dormant identity-verification extension point (no provider, no documents, no biometrics).
  CONSTRAINT platform_mfa_recovery_evidence_chk
    CHECK ((evidence_type IS NULL AND evidence_ref IS NULL)
           OR (evidence_type = 'identity_verification' AND length(evidence_ref) BETWEEN 1 AND 200))
);

CREATE UNIQUE INDEX platform_mfa_recovery_requests_one_active_per_target
  ON public.platform_mfa_recovery_requests (target_user_id)
  WHERE status IN ('requested', 'approved', 'executed_awaiting_enrolment');

CREATE INDEX platform_mfa_recovery_requests_created_idx
  ON public.platform_mfa_recovery_requests (created_at DESC);

COMMENT ON TABLE public.platform_mfa_recovery_requests IS
  'G7F-3C3 privileged MFA recovery requests (Option D). Mutated only by service_role recovery RPCs. grant_hash is a SHA-256 digest of the one-time grant and is not readable by any client role.';

-- ---------------------------------------------------------------------------------------------
-- 3. Recovery locks: a row here suspends all platform authority for user_id
-- ---------------------------------------------------------------------------------------------
CREATE TABLE public.platform_mfa_recovery_locks (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  request_id uuid NOT NULL REFERENCES public.platform_mfa_recovery_requests(id) ON DELETE CASCADE,
  locked_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.platform_mfa_recovery_locks IS
  'G7F-3C3: users whose MFA factor was removed by recovery. is_super_owner/is_super_admin return false while a row exists. Removed only by complete_platform_mfa_recovery; expiry never removes it.';

-- ---------------------------------------------------------------------------------------------
-- 4. Client access: RLS on, no policies, no client grants; service_role read-only minus grant_hash
-- ---------------------------------------------------------------------------------------------
ALTER TABLE public.platform_mfa_recovery_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_mfa_recovery_locks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.platform_mfa_recovery_requests FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.platform_mfa_recovery_locks FROM PUBLIC, anon, authenticated, service_role;

GRANT SELECT (
  id, target_user_id, target_kind, target_factor_id,
  requested_by, approved_by, approved_at, second_approved_by, second_approved_at,
  executed_by, cancelled_by, reason, terminal_reason, cooling_off_until, status,
  created_at, executed_at, completed_at, cancelled_at, expires_at,
  grant_issued_at, grant_expires_at, grant_redeemed_at, replacement_factor_id,
  evidence_type, updated_at
) ON public.platform_mfa_recovery_requests TO service_role;
GRANT SELECT ON public.platform_mfa_recovery_locks TO service_role;

-- ---------------------------------------------------------------------------------------------
-- 5. Write guard + lifecycle trigger
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION public.g7f3c3_guard_recovery_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user uuid;
BEGIN
  IF pg_catalog.current_setting('g7f3c3.rpc', true) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  IF TG_OP = 'DELETE' THEN
    IF TG_TABLE_NAME = 'platform_mfa_recovery_locks' THEN
      v_user := OLD.user_id;
    ELSE
      v_user := OLD.target_user_id;
    END IF;
    -- Cascade from auth.users deletion only.
    IF NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = v_user) THEN
      RETURN OLD;
    END IF;
  END IF;
  RAISE EXCEPTION 'mfa_recovery_state_rpc_only' USING ERRCODE = 'insufficient_privilege';
END;
$$;

CREATE FUNCTION public.g7f3c3_validate_recovery_transition()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'requested' OR NEW.executed_at IS NOT NULL OR NEW.grant_hash IS NOT NULL
       OR NEW.second_approved_by IS NOT NULL OR NEW.completed_at IS NOT NULL OR NEW.cancelled_at IS NOT NULL
       OR NEW.grant_redeemed_at IS NOT NULL OR NEW.replacement_factor_id IS NOT NULL THEN
      RAISE EXCEPTION 'mfa_recovery_invalid_initial_state' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.status IN ('completed', 'cancelled', 'expired', 'denied', 'failed') THEN
    RAISE EXCEPTION 'mfa_recovery_terminal_state' USING ERRCODE = 'check_violation';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.target_user_id IS DISTINCT FROM OLD.target_user_id
     OR NEW.target_kind IS DISTINCT FROM OLD.target_kind
     OR NEW.target_factor_id IS DISTINCT FROM OLD.target_factor_id
     OR NEW.requested_by IS DISTINCT FROM OLD.requested_by
     OR NEW.requested_session_id IS DISTINCT FROM OLD.requested_session_id
     OR NEW.approved_by IS DISTINCT FROM OLD.approved_by
     OR NEW.approved_session_id IS DISTINCT FROM OLD.approved_session_id
     OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
     OR NEW.reason IS DISTINCT FROM OLD.reason
     OR NEW.created_at IS DISTINCT FROM OLD.created_at
     OR NEW.cooling_off_until IS DISTINCT FROM OLD.cooling_off_until
     OR NEW.evidence_type IS DISTINCT FROM OLD.evidence_type
     OR NEW.evidence_ref IS DISTINCT FROM OLD.evidence_ref THEN
    RAISE EXCEPTION 'mfa_recovery_immutable_field' USING ERRCODE = 'check_violation';
  END IF;

  IF OLD.second_approved_by IS NOT NULL AND (
       NEW.second_approved_by IS DISTINCT FROM OLD.second_approved_by
       OR NEW.second_session_id IS DISTINCT FROM OLD.second_session_id
       OR NEW.second_approved_at IS DISTINCT FROM OLD.second_approved_at) THEN
    RAISE EXCEPTION 'mfa_recovery_immutable_field' USING ERRCODE = 'check_violation';
  END IF;

  IF OLD.executed_at IS NOT NULL AND (
       NEW.executed_at IS DISTINCT FROM OLD.executed_at
       OR NEW.executed_by IS DISTINCT FROM OLD.executed_by
       OR NEW.executed_session_id IS DISTINCT FROM OLD.executed_session_id) THEN
    RAISE EXCEPTION 'mfa_recovery_immutable_field' USING ERRCODE = 'check_violation';
  END IF;

  IF NOT (
       (OLD.status = 'requested' AND NEW.status IN ('approved', 'executed_awaiting_enrolment', 'cancelled', 'expired', 'denied'))
    OR (OLD.status = 'approved' AND NEW.status IN ('executed_awaiting_enrolment', 'cancelled', 'expired', 'denied'))
    OR (OLD.status = 'executed_awaiting_enrolment' AND NEW.status IN ('executed_awaiting_enrolment', 'completed', 'expired', 'failed'))
  ) THEN
    RAISE EXCEPTION 'mfa_recovery_invalid_transition' USING ERRCODE = 'check_violation';
  END IF;

  NEW.updated_at := pg_catalog.now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER platform_mfa_recovery_requests_guard
  BEFORE INSERT OR UPDATE OR DELETE ON public.platform_mfa_recovery_requests
  FOR EACH ROW EXECUTE FUNCTION public.g7f3c3_guard_recovery_write();

CREATE TRIGGER platform_mfa_recovery_requests_lifecycle
  BEFORE INSERT OR UPDATE ON public.platform_mfa_recovery_requests
  FOR EACH ROW EXECUTE FUNCTION public.g7f3c3_validate_recovery_transition();

CREATE TRIGGER platform_mfa_recovery_locks_guard
  BEFORE INSERT OR UPDATE OR DELETE ON public.platform_mfa_recovery_locks
  FOR EACH ROW EXECUTE FUNCTION public.g7f3c3_guard_recovery_write();

-- ---------------------------------------------------------------------------------------------
-- 6. Recovery lock in the authoritative platform authority primitives
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION public.is_platform_mfa_recovery_locked(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p_user_id IS NOT NULL
    AND EXISTS (SELECT 1 FROM public.platform_mfa_recovery_locks l WHERE l.user_id = p_user_id);
$$;

CREATE OR REPLACE FUNCTION public.is_super_owner(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (SELECT 1 FROM public.platform_roles pr WHERE pr.user_id = p_user_id AND pr.role = 'super_owner')
    AND NOT public.is_platform_mfa_recovery_locked(p_user_id);
$$;

CREATE OR REPLACE FUNCTION public.is_super_admin(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (SELECT 1 FROM public.platform_roles pr WHERE pr.user_id = p_user_id AND pr.role = 'super_admin')
    AND NOT public.is_platform_mfa_recovery_locked(p_user_id);
$$;

-- ---------------------------------------------------------------------------------------------
-- 7. Internal helpers (no grants: callable only from the SECURITY DEFINER RPCs below)
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION public.g7f3c3_fp(p_id uuid)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE WHEN p_id IS NULL THEN NULL
    ELSE left(encode(pg_catalog.sha256(p_id::text::bytea), 'hex'), 12) END;
$$;

CREATE FUNCTION public.g7f3c3_mode(p_mode text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE WHEN p_mode IN ('disabled', 'audit', 'enforce') THEN p_mode ELSE 'unknown' END;
$$;

CREATE FUNCTION public.g7f3c3_has_role(p_user uuid, p_role text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (SELECT 1 FROM public.platform_roles pr WHERE pr.user_id = p_user AND pr.role::text = p_role);
$$;

CREATE FUNCTION public.g7f3c3_has_verified_totp(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM auth.mfa_factors f
    WHERE f.user_id = p_user AND f.status::text = 'verified' AND f.factor_type::text = 'totp'
  );
$$;

CREATE FUNCTION public.g7f3c3_in_recovery(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT public.is_platform_mfa_recovery_locked(p_user)
    OR EXISTS (
      SELECT 1 FROM public.platform_mfa_recovery_requests r
      WHERE r.target_user_id = p_user
        AND r.status IN ('requested', 'approved', 'executed_awaiting_enrolment')
    );
$$;

-- Usable normal Super Owner: super_owner role, not active break-glass, not locked, verified TOTP.
CREATE FUNCTION public.g7f3c3_usable_normal_so(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p_user IS NOT NULL
    AND public.g7f3c3_has_role(p_user, 'super_owner')
    AND NOT public.is_active_break_glass(p_user)
    AND NOT public.is_platform_mfa_recovery_locked(p_user)
    AND public.g7f3c3_has_verified_totp(p_user);
$$;

-- Usable break-glass: super_owner role, active break-glass, not locked, verified TOTP.
CREATE FUNCTION public.g7f3c3_usable_bg(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p_user IS NOT NULL
    AND public.g7f3c3_has_role(p_user, 'super_owner')
    AND public.is_active_break_glass(p_user)
    AND NOT public.is_platform_mfa_recovery_locked(p_user)
    AND public.g7f3c3_has_verified_totp(p_user);
$$;

CREATE FUNCTION public.g7f3c3_target_kind(p_user uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT CASE
    WHEN public.g7f3c3_has_role(p_user, 'super_owner') AND public.is_active_break_glass(p_user) THEN 'break_glass'
    WHEN public.g7f3c3_has_role(p_user, 'super_owner') THEN 'normal_so'
    WHEN public.g7f3c3_has_role(p_user, 'super_admin') THEN 'super_admin'
    ELSE NULL
  END;
$$;

-- Final recovery path: after locking p_target there must remain
-- (>=1 usable normal SO AND >=1 usable BG) OR >=2 usable normal SOs; a BG target needs >=2 normal SOs.
CREATE FUNCTION public.g7f3c3_final_path_formula(p_normal_so integer, p_bg integer, p_target_kind text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE
    WHEN p_target_kind = 'break_glass' THEN COALESCE(p_normal_so, 0) >= 2
    ELSE (COALESCE(p_normal_so, 0) >= 1 AND COALESCE(p_bg, 0) >= 1) OR COALESCE(p_normal_so, 0) >= 2
  END;
$$;

CREATE FUNCTION public.g7f3c3_final_path_counts(p_target uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'usable_normal_so', (
      SELECT count(DISTINCT pr.user_id)::integer FROM public.platform_roles pr
      WHERE pr.role::text = 'super_owner' AND pr.user_id <> p_target
        AND public.g7f3c3_usable_normal_so(pr.user_id)),
    'usable_bg', (
      SELECT count(DISTINCT pr.user_id)::integer FROM public.platform_roles pr
      WHERE pr.role::text = 'super_owner' AND pr.user_id <> p_target
        AND public.g7f3c3_usable_bg(pr.user_id))
  );
$$;

CREATE FUNCTION public.g7f3c3_final_path_ok(p_target uuid, p_target_kind text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb := public.g7f3c3_final_path_counts(p_target);
BEGIN
  RETURN public.g7f3c3_final_path_formula((v->>'usable_normal_so')::integer, (v->>'usable_bg')::integer, p_target_kind);
END;
$$;

-- Server-side fresh-auth re-check from Auth state: session belongs to user, not expired,
-- optional aal2, optional TOTP AMR refreshed within p_fresh_sec. NULL = satisfied, else reason.
CREATE FUNCTION public.g7f3c3_session_check(p_user uuid, p_session uuid, p_require_aal2 boolean, p_fresh_sec integer)
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user uuid;
  v_aal text;
  v_not_after timestamptz;
  v_amr timestamptz;
BEGIN
  IF p_user IS NULL OR p_session IS NULL THEN
    RETURN 'session_missing';
  END IF;
  SELECT s.user_id, s.aal::text, s.not_after INTO v_user, v_aal, v_not_after
  FROM auth.sessions s WHERE s.id = p_session;
  IF NOT FOUND THEN
    RETURN 'session_missing';
  END IF;
  IF v_user <> p_user THEN
    RETURN 'session_user_mismatch';
  END IF;
  IF v_not_after IS NOT NULL AND v_not_after <= pg_catalog.now() THEN
    RETURN 'session_expired';
  END IF;
  IF p_require_aal2 AND v_aal IS DISTINCT FROM 'aal2' THEN
    RETURN 'aal_insufficient';
  END IF;
  IF p_fresh_sec IS NOT NULL THEN
    SELECT max(c.updated_at) INTO v_amr
    FROM auth.mfa_amr_claims c
    WHERE c.session_id = p_session AND c.authentication_method IN ('totp', 'mfa/totp');
    IF v_amr IS NULL THEN
      RETURN 'fresh_mfa_missing';
    END IF;
    IF v_amr < pg_catalog.now() - pg_catalog.make_interval(secs => p_fresh_sec) THEN
      RETURN 'fresh_mfa_stale';
    END IF;
  END IF;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.g7f3c3_audit(p_event text, p_actor uuid, p_subject uuid, p_meta jsonb)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  INSERT INTO public.security_audit_events (event_type, acting_user_id, subject_user_id, metadata)
  VALUES (
    p_event,
    p_actor,
    p_subject,
    jsonb_build_object('source', 'g7f3c3_mfa_recovery', 'authoritative', true) || COALESCE(p_meta, '{}'::jsonb)
  );
$$;

CREATE FUNCTION public.g7f3c3_deny(
  p_action text, p_reason text, p_actor uuid, p_actor_session uuid,
  p_target uuid, p_request uuid, p_mode text, p_extra jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_DENIED', p_actor, p_target,
    jsonb_build_object(
      'action', p_action,
      'result_reason', p_reason,
      'request_id', p_request,
      'actor_session_fp', public.g7f3c3_fp(p_actor_session),
      'mode', public.g7f3c3_mode(p_mode)
    ) || COALESCE(p_extra, '{}'::jsonb));
  RETURN jsonb_build_object('ok', false, 'reason', p_reason, 'request_id', p_request);
END;
$$;

CREATE FUNCTION public.g7f3c3_lock_target(p_target uuid, p_global boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_global THEN
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('g7f3c3:global', 0));
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('g7f3c3:target:' || p_target::text, 0));
END;
$$;

-- Returns the row locked FOR UPDATE after taking the advisory lock(s); NULL row when missing.
CREATE FUNCTION public.g7f3c3_lock_request(p_request uuid, p_global boolean)
RETURNS public.platform_mfa_recovery_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_target uuid;
  r public.platform_mfa_recovery_requests;
BEGIN
  SELECT target_user_id INTO v_target FROM public.platform_mfa_recovery_requests WHERE id = p_request;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  PERFORM public.g7f3c3_lock_target(v_target, p_global);
  SELECT * INTO r FROM public.platform_mfa_recovery_requests WHERE id = p_request FOR UPDATE;
  RETURN r;
END;
$$;

-- Lazily expires an active request whose window has elapsed. An executed request stays locked.
CREATE FUNCTION public.g7f3c3_expire_if_due(p_req public.platform_mfa_recovery_requests, p_mode text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_req.id IS NULL
     OR p_req.status NOT IN ('requested', 'approved', 'executed_awaiting_enrolment')
     OR pg_catalog.now() < p_req.expires_at THEN
    RETURN false;
  END IF;
  UPDATE public.platform_mfa_recovery_requests
  SET status = 'expired',
      terminal_reason = CASE WHEN p_req.executed_at IS NULL THEN 'execution_window_elapsed'
                             ELSE 'enrolment_window_elapsed' END
  WHERE id = p_req.id;
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_EXPIRED', NULL, p_req.target_user_id,
    jsonb_build_object(
      'request_id', p_req.id,
      'target_kind', p_req.target_kind,
      'previous_status', p_req.status,
      'expires_at', p_req.expires_at,
      'target_remains_locked', p_req.executed_at IS NOT NULL,
      'mode', public.g7f3c3_mode(p_mode)
    ));
  RETURN true;
END;
$$;

CREATE FUNCTION public.g7f3c3_authority_snapshot(p_user uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'platform_roles', (SELECT COALESCE(jsonb_agg(pr.id ORDER BY pr.id), '[]'::jsonb) FROM public.platform_roles pr WHERE pr.user_id = p_user),
    'tenant_memberships', (SELECT COALESCE(jsonb_agg(jsonb_build_array(tm.id, tm.role, tm.active) ORDER BY tm.id), '[]'::jsonb)
                           FROM public.tenant_memberships tm WHERE tm.user_id = p_user),
    'super_admin_grants', (SELECT COALESCE(jsonb_agg(jsonb_build_array(g.id, g.access_level, g.revoked_at, g.expires_at) ORDER BY g.id), '[]'::jsonb)
                           FROM public.super_admin_tenant_access g WHERE g.user_id = p_user),
    'support_grants', (SELECT COALESCE(jsonb_agg(jsonb_build_array(g.id, g.revoked_at) ORDER BY g.id), '[]'::jsonb)
                       FROM public.tenant_support_access_grants g WHERE g.grantee_user_id = p_user),
    'emergency_grants', (SELECT COALESCE(jsonb_agg(jsonb_build_array(g.id, g.revoked_at) ORDER BY g.id), '[]'::jsonb)
                         FROM public.tenant_emergency_access_grants g WHERE g.grantee_user_id = p_user)
  );
$$;

-- Removes every MFA factor, refresh token and Auth session of p_target. Not granted to anyone.
CREATE FUNCTION public.g7f3c3_revoke_target_auth(p_target uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_factor_ids jsonb;
  v_factors integer := 0;
  v_refresh integer := 0;
  v_sessions integer := 0;
BEGIN
  SELECT COALESCE(jsonb_agg(f.id ORDER BY f.created_at), '[]'::jsonb) INTO v_factor_ids
  FROM auth.mfa_factors f WHERE f.user_id = p_target;
  DELETE FROM auth.mfa_factors WHERE user_id = p_target;
  GET DIAGNOSTICS v_factors = ROW_COUNT;
  DELETE FROM auth.refresh_tokens WHERE user_id = p_target::text;
  GET DIAGNOSTICS v_refresh = ROW_COUNT;
  DELETE FROM auth.sessions WHERE user_id = p_target;
  GET DIAGNOSTICS v_sessions = ROW_COUNT;
  RETURN jsonb_build_object(
    'removed_factor_ids', v_factor_ids,
    'factors_removed_count', v_factors,
    'refresh_revoked_count', v_refresh,
    'sessions_revoked_count', v_sessions
  );
END;
$$;

CREATE FUNCTION public.g7f3c3_assert_target_revoked(p_target uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM auth.mfa_factors WHERE user_id = p_target) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:factors_remain';
  END IF;
  IF EXISTS (SELECT 1 FROM auth.sessions WHERE user_id = p_target) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:sessions_remain';
  END IF;
  IF EXISTS (SELECT 1 FROM auth.refresh_tokens WHERE user_id = p_target::text) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:refresh_remain';
  END IF;
  IF EXISTS (SELECT 1 FROM public.platform_tenant_access_sessions WHERE platform_user_id = p_target AND ended_at IS NULL) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:g7d_open';
  END IF;
  IF EXISTS (SELECT 1 FROM public.platform_break_glass_sessions WHERE user_id = p_target AND ended_at IS NULL) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:bg_session_open';
  END IF;
  IF NOT public.is_platform_mfa_recovery_locked(p_target) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:lock_missing';
  END IF;
  IF public.is_super_owner(p_target) OR public.is_super_admin(p_target) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:authority_not_suspended';
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------------------------
-- 8. RPC implementations (not granted; wrappers set the write-guard flag)
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION public.g7f3c3_request_impl(
  p_actor uuid, p_session uuid, p_target uuid, p_reason text, p_cooling_off_minutes integer, p_mode text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now timestamptz := pg_catalog.now();
  v_reason text := btrim(COALESCE(p_reason, ''));
  v_kind text;
  v_check text;
  v_verified_count integer;
  v_factor uuid;
  v_cool timestamptz;
  v_id uuid;
  v_counts jsonb;
  r public.platform_mfa_recovery_requests;
BEGIN
  IF p_actor IS NULL OR p_target IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  PERFORM public.g7f3c3_lock_target(p_target, false);

  FOR r IN
    SELECT * FROM public.platform_mfa_recovery_requests
    WHERE target_user_id = p_target AND status IN ('requested', 'approved', 'executed_awaiting_enrolment')
    FOR UPDATE
  LOOP
    PERFORM public.g7f3c3_expire_if_due(r, p_mode);
  END LOOP;

  IF p_actor = p_target THEN
    RETURN public.g7f3c3_deny('request', 'self_recovery_denied', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  v_check := public.g7f3c3_session_check(p_actor, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('request', v_check, p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  IF NOT public.g7f3c3_usable_normal_so(p_actor) THEN
    RETURN public.g7f3c3_deny('request', 'actor_not_recovery_authority', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  IF public.g7f3c3_in_recovery(p_actor) THEN
    RETURN public.g7f3c3_deny('request', 'actor_in_recovery', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  v_kind := public.g7f3c3_target_kind(p_target);
  IF v_kind IS NULL THEN
    RETURN public.g7f3c3_deny('request', 'target_not_privileged', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  IF length(v_reason) < 10 OR length(v_reason) > 500 THEN
    RETURN public.g7f3c3_deny('request', 'reason_invalid', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  IF EXISTS (SELECT 1 FROM public.platform_mfa_recovery_requests
             WHERE target_user_id = p_target AND status IN ('requested', 'approved', 'executed_awaiting_enrolment')) THEN
    RETURN public.g7f3c3_deny('request', 'active_request_exists', p_actor, p_session, p_target, NULL, p_mode);
  END IF;

  SELECT count(*)::integer, (array_agg(f.id))[1] INTO v_verified_count, v_factor
  FROM auth.mfa_factors f WHERE f.user_id = p_target AND f.status::text = 'verified';
  IF v_verified_count > 1 THEN
    RETURN public.g7f3c3_deny('request', 'target_factor_ambiguous', p_actor, p_session, p_target, NULL, p_mode);
  END IF;
  IF v_verified_count = 0 AND NOT public.is_platform_mfa_recovery_locked(p_target) THEN
    RETURN public.g7f3c3_deny('request', 'target_has_no_verified_factor', p_actor, p_session, p_target, NULL, p_mode);
  END IF;

  IF v_kind IN ('normal_so', 'break_glass') AND NOT public.g7f3c3_final_path_ok(p_target, v_kind) THEN
    v_counts := public.g7f3c3_final_path_counts(p_target);
    RETURN public.g7f3c3_deny('request', 'final_recovery_path_violation', p_actor, p_session, p_target, NULL, p_mode, v_counts);
  END IF;

  IF v_kind = 'super_admin' THEN
    v_cool := v_now;
  ELSE
    IF p_cooling_off_minutes IS NULL OR p_cooling_off_minutes < 15 OR p_cooling_off_minutes > 10080 THEN
      RETURN public.g7f3c3_deny('request', 'cooling_off_invalid', p_actor, p_session, p_target, NULL, p_mode);
    END IF;
    v_cool := v_now + pg_catalog.make_interval(mins => p_cooling_off_minutes);
  END IF;

  INSERT INTO public.platform_mfa_recovery_requests (
    target_user_id, target_kind, target_factor_id,
    requested_by, requested_session_id, approved_by, approved_session_id, approved_at,
    reason, cooling_off_until, status, created_at, expires_at
  ) VALUES (
    p_target, v_kind, v_factor,
    p_actor, p_session, p_actor, p_session, v_now,
    v_reason, v_cool, 'requested', v_now, v_cool + interval '60 minutes'
  ) RETURNING id INTO v_id;

  PERFORM public.g7f3c3_audit('MFA_RECOVERY_REQUESTED', p_actor, p_target, jsonb_build_object(
    'request_id', v_id,
    'target_kind', v_kind,
    'target_factor_id', v_factor,
    'reason', v_reason,
    'cooling_off_until', v_cool,
    'expires_at', v_cool + interval '60 minutes',
    'requires_second_approval', v_kind = 'break_glass',
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_APPROVED', p_actor, p_target, jsonb_build_object(
    'request_id', v_id,
    'target_kind', v_kind,
    'approval_index', 1,
    'approval_basis', 'initiator_normal_super_owner',
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));

  RETURN jsonb_build_object(
    'ok', true,
    'request_id', v_id,
    'target_kind', v_kind,
    'status', 'requested',
    'cooling_off_until', v_cool,
    'expires_at', v_cool + interval '60 minutes',
    'requires_second_approval', v_kind = 'break_glass'
  );
END;
$$;

CREATE FUNCTION public.g7f3c3_approve_impl(p_actor uuid, p_session uuid, p_request uuid, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  r public.platform_mfa_recovery_requests;
  v_check text;
  v_basis text;
BEGIN
  IF p_actor IS NULL OR p_request IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  r := public.g7f3c3_lock_request(p_request, false);
  IF r.id IS NULL THEN
    RETURN public.g7f3c3_deny('approve', 'request_not_found', p_actor, p_session, NULL, p_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('approve', 'request_expired', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF r.status <> 'requested' THEN
    RETURN public.g7f3c3_deny('approve', 'request_not_pending', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  IF r.target_kind = 'super_admin' THEN
    RETURN public.g7f3c3_deny('approve', 'second_approval_not_applicable', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_actor = r.target_user_id THEN
    RETURN public.g7f3c3_deny('approve', 'self_approval_denied', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_actor = r.requested_by OR p_actor = r.approved_by THEN
    RETURN public.g7f3c3_deny('approve', 'approver_not_distinct', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  v_check := public.g7f3c3_session_check(p_actor, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('approve', v_check, p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_session = r.approved_session_id THEN
    RETURN public.g7f3c3_deny('approve', 'approval_session_not_distinct', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF public.g7f3c3_usable_normal_so(p_actor) THEN
    v_basis := 'normal_super_owner';
  ELSIF r.target_kind = 'normal_so' AND public.g7f3c3_usable_bg(p_actor) THEN
    v_basis := 'break_glass';
  ELSE
    RETURN public.g7f3c3_deny('approve', 'actor_not_recovery_authority', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF public.g7f3c3_in_recovery(p_actor) THEN
    RETURN public.g7f3c3_deny('approve', 'actor_in_recovery', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;

  UPDATE public.platform_mfa_recovery_requests
  SET second_approved_by = p_actor,
      second_session_id = p_session,
      second_approved_at = pg_catalog.now(),
      status = 'approved'
  WHERE id = r.id;

  PERFORM public.g7f3c3_audit('MFA_RECOVERY_SECOND_APPROVAL', p_actor, r.target_user_id, jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'approval_index', 2,
    'approval_basis', v_basis,
    'expedites_cooling_off', r.target_kind = 'normal_so',
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));

  RETURN jsonb_build_object('ok', true, 'request_id', r.id, 'status', 'approved', 'approval_basis', v_basis);
END;
$$;

CREATE FUNCTION public.g7f3c3_execute_impl(p_actor uuid, p_session uuid, p_request uuid, p_grant_hash text, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  r public.platform_mfa_recovery_requests;
  v_now timestamptz := pg_catalog.now();
  v_check text;
  v_second_ok boolean;
  v_verified uuid[];
  v_before jsonb;
  v_after jsonb;
  v_revoked jsonb;
  v_g7d integer := 0;
  v_bg integer := 0;
  v_bg_row public.platform_break_glass_sessions;
  v_counts jsonb;
  v_meta jsonb;
BEGIN
  IF p_actor IS NULL OR p_request IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  r := public.g7f3c3_lock_request(p_request, true);
  IF r.id IS NULL THEN
    RETURN public.g7f3c3_deny('execute', 'request_not_found', p_actor, p_session, NULL, p_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('execute', 'request_expired', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF r.status NOT IN ('requested', 'approved') THEN
    RETURN public.g7f3c3_deny('execute', 'request_not_executable', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  IF r.target_kind = 'break_glass' AND r.status <> 'approved' THEN
    RETURN public.g7f3c3_deny('execute', 'second_approval_required', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF (r.target_kind = 'break_glass' OR (r.target_kind = 'normal_so' AND r.status = 'requested'))
     AND v_now < r.cooling_off_until THEN
    RETURN public.g7f3c3_deny('execute', 'cooling_off_active', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('cooling_off_until', r.cooling_off_until));
  END IF;

  IF p_actor = r.target_user_id THEN
    RETURN public.g7f3c3_deny('execute', 'self_recovery_denied', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_actor IS DISTINCT FROM r.requested_by AND p_actor IS DISTINCT FROM r.second_approved_by THEN
    RETURN public.g7f3c3_deny('execute', 'executor_not_request_authority', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  v_check := public.g7f3c3_session_check(p_actor, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('execute', v_check, p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF NOT public.g7f3c3_usable_normal_so(p_actor) THEN
    RETURN public.g7f3c3_deny('execute', 'actor_not_recovery_authority', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF public.g7f3c3_in_recovery(p_actor) THEN
    RETURN public.g7f3c3_deny('execute', 'actor_in_recovery', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;

  -- Approvers must still hold their authority now.
  IF NOT public.g7f3c3_usable_normal_so(r.approved_by) OR public.g7f3c3_in_recovery(r.approved_by) THEN
    UPDATE public.platform_mfa_recovery_requests SET status = 'denied', terminal_reason = 'approver_no_longer_qualified'
    WHERE id = r.id;
    RETURN public.g7f3c3_deny('execute', 'approver_no_longer_qualified', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('approval_index', 1, 'request_terminal', true));
  END IF;
  IF r.second_approved_by IS NOT NULL THEN
    v_second_ok := (public.g7f3c3_usable_normal_so(r.second_approved_by)
                    OR (r.target_kind = 'normal_so' AND public.g7f3c3_usable_bg(r.second_approved_by)))
                   AND NOT public.g7f3c3_in_recovery(r.second_approved_by);
    IF NOT v_second_ok THEN
      UPDATE public.platform_mfa_recovery_requests SET status = 'denied', terminal_reason = 'approver_no_longer_qualified'
      WHERE id = r.id;
      RETURN public.g7f3c3_deny('execute', 'approver_no_longer_qualified', p_actor, p_session, r.target_user_id, r.id, p_mode,
        jsonb_build_object('approval_index', 2, 'request_terminal', true));
    END IF;
  END IF;

  IF public.g7f3c3_target_kind(r.target_user_id) IS DISTINCT FROM r.target_kind THEN
    UPDATE public.platform_mfa_recovery_requests SET status = 'denied', terminal_reason = 'target_kind_changed'
    WHERE id = r.id;
    RETURN public.g7f3c3_deny('execute', 'target_kind_changed', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('request_terminal', true));
  END IF;

  IF r.target_kind IN ('normal_so', 'break_glass') AND NOT public.g7f3c3_final_path_ok(r.target_user_id, r.target_kind) THEN
    v_counts := public.g7f3c3_final_path_counts(r.target_user_id);
    RETURN public.g7f3c3_deny('execute', 'final_recovery_path_violation', p_actor, p_session, r.target_user_id, r.id, p_mode, v_counts);
  END IF;

  SELECT COALESCE(array_agg(f.id), '{}') INTO v_verified
  FROM auth.mfa_factors f WHERE f.user_id = r.target_user_id AND f.status::text = 'verified';
  IF (r.target_factor_id IS NOT NULL AND v_verified IS DISTINCT FROM ARRAY[r.target_factor_id])
     OR (r.target_factor_id IS NULL AND cardinality(v_verified) <> 0) THEN
    UPDATE public.platform_mfa_recovery_requests SET status = 'denied', terminal_reason = 'target_factor_changed'
    WHERE id = r.id;
    RETURN public.g7f3c3_deny('execute', 'target_factor_changed', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('bound_factor_id', r.target_factor_id, 'verified_factor_count', cardinality(v_verified), 'request_terminal', true));
  END IF;

  IF p_grant_hash IS NULL OR p_grant_hash !~ '^[0-9a-f]{64}$' THEN
    RETURN public.g7f3c3_deny('execute', 'grant_hash_invalid', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;

  -- Destructive section: everything below commits or rolls back together.
  v_before := public.g7f3c3_authority_snapshot(r.target_user_id);
  v_revoked := public.g7f3c3_revoke_target_auth(r.target_user_id);

  UPDATE public.platform_tenant_access_sessions
  SET ended_at = v_now
  WHERE platform_user_id = r.target_user_id AND ended_at IS NULL;
  GET DIAGNOSTICS v_g7d = ROW_COUNT;

  FOR v_bg_row IN
    SELECT * FROM public.platform_break_glass_sessions
    WHERE user_id = r.target_user_id AND ended_at IS NULL
    FOR UPDATE
  LOOP
    PERFORM public._end_break_glass_platform_session_row(v_bg_row, 'mfa_recovery', v_now);
    v_bg := v_bg + 1;
  END LOOP;

  INSERT INTO public.platform_mfa_recovery_locks (user_id, request_id, locked_at)
  VALUES (r.target_user_id, r.id, v_now)
  ON CONFLICT (user_id) DO UPDATE SET request_id = EXCLUDED.request_id, locked_at = EXCLUDED.locked_at;

  UPDATE public.platform_mfa_recovery_requests
  SET status = 'executed_awaiting_enrolment',
      executed_at = v_now,
      executed_by = p_actor,
      executed_session_id = p_session,
      expires_at = v_now + interval '24 hours',
      grant_hash = p_grant_hash,
      grant_issued_at = v_now,
      grant_expires_at = v_now + interval '30 minutes',
      grant_redeemed_at = NULL,
      redeemed_session_id = NULL,
      grant_failed_attempts = 0
  WHERE id = r.id;

  v_meta := jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  );
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_EXECUTED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'expedited', r.status = 'approved' AND r.target_kind = 'normal_so',
    'second_approved_by', r.second_approved_by,
    'recovery_expires_at', v_now + interval '24 hours'
  ));
  PERFORM public.g7f3c3_audit('MFA_FACTOR_REMOVED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'removed_factor_ids', v_revoked->'removed_factor_ids',
    'factors_removed_count', v_revoked->'factors_removed_count',
    'bound_factor_id', r.target_factor_id,
    'reason_code', 'mfa_recovery'
  ));
  PERFORM public.g7f3c3_audit('MFA_TARGET_SESSIONS_REVOKED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'sessions_revoked_count', v_revoked->'sessions_revoked_count',
    'refresh_revoked_count', v_revoked->'refresh_revoked_count',
    'reason_code', 'mfa_recovery'
  ));
  IF v_g7d > 0 THEN
    PERFORM public.g7f3c3_audit('PLATFORM_TENANT_ENTRY_ENDED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
      'g7d_ended_count', v_g7d, 'end_reason', 'mfa_recovery'));
  END IF;
  IF v_bg > 0 THEN
    PERFORM public.g7f3c3_audit('BREAK_GLASS_SESSION_ENDED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
      'bg_sessions_ended_count', v_bg, 'end_reason', 'mfa_recovery'));
  END IF;
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_GRANT_ISSUED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'grant_expires_at', v_now + interval '30 minutes',
    'reissue', false
  ));

  PERFORM public.g7f3c3_assert_target_revoked(r.target_user_id);
  v_after := public.g7f3c3_authority_snapshot(r.target_user_id);
  IF v_after IS DISTINCT FROM v_before THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:authority_records_changed';
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'request_id', r.id,
    'status', 'executed_awaiting_enrolment',
    'target_user_id', r.target_user_id,
    'grant_expires_at', v_now + interval '30 minutes',
    'recovery_expires_at', v_now + interval '24 hours',
    'factors_removed_count', v_revoked->'factors_removed_count',
    'sessions_revoked_count', v_revoked->'sessions_revoked_count',
    'refresh_revoked_count', v_revoked->'refresh_revoked_count',
    'g7d_ended_count', v_g7d,
    'bg_sessions_ended_count', v_bg
  );
END;
$$;

CREATE FUNCTION public.g7f3c3_reissue_impl(p_actor uuid, p_session uuid, p_request uuid, p_grant_hash text, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  r public.platform_mfa_recovery_requests;
  v_now timestamptz := pg_catalog.now();
  v_check text;
  v_before jsonb;
  v_revoked jsonb;
  v_meta jsonb;
BEGIN
  IF p_actor IS NULL OR p_request IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  r := public.g7f3c3_lock_request(p_request, false);
  IF r.id IS NULL THEN
    RETURN public.g7f3c3_deny('reissue', 'request_not_found', p_actor, p_session, NULL, p_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('reissue', 'request_expired', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF r.status <> 'executed_awaiting_enrolment' THEN
    RETURN public.g7f3c3_deny('reissue', 'recovery_not_awaiting_enrolment', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  IF p_actor = r.target_user_id THEN
    RETURN public.g7f3c3_deny('reissue', 'self_recovery_denied', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_actor IS DISTINCT FROM r.requested_by AND p_actor IS DISTINCT FROM r.executed_by
     AND p_actor IS DISTINCT FROM r.second_approved_by THEN
    RETURN public.g7f3c3_deny('reissue', 'executor_not_request_authority', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  v_check := public.g7f3c3_session_check(p_actor, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('reissue', v_check, p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF NOT public.g7f3c3_usable_normal_so(p_actor) OR public.g7f3c3_in_recovery(p_actor) THEN
    RETURN public.g7f3c3_deny('reissue', 'actor_not_recovery_authority', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_grant_hash IS NULL OR p_grant_hash !~ '^[0-9a-f]{64}$' THEN
    RETURN public.g7f3c3_deny('reissue', 'grant_hash_invalid', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;

  v_before := public.g7f3c3_authority_snapshot(r.target_user_id);
  -- Anything enrolled or signed in since execution is discarded with the old grant.
  v_revoked := public.g7f3c3_revoke_target_auth(r.target_user_id);

  UPDATE public.platform_mfa_recovery_requests
  SET grant_hash = p_grant_hash,
      grant_issued_at = v_now,
      grant_expires_at = v_now + interval '30 minutes',
      grant_redeemed_at = NULL,
      redeemed_session_id = NULL,
      grant_failed_attempts = 0
  WHERE id = r.id;

  v_meta := jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  );
  IF (v_revoked->>'factors_removed_count')::integer > 0 THEN
    PERFORM public.g7f3c3_audit('MFA_FACTOR_REMOVED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
      'removed_factor_ids', v_revoked->'removed_factor_ids',
      'factors_removed_count', v_revoked->'factors_removed_count',
      'reason_code', 'mfa_recovery_grant_reissue'));
  END IF;
  PERFORM public.g7f3c3_audit('MFA_TARGET_SESSIONS_REVOKED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'sessions_revoked_count', v_revoked->'sessions_revoked_count',
    'refresh_revoked_count', v_revoked->'refresh_revoked_count',
    'reason_code', 'mfa_recovery_grant_reissue'));
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_GRANT_ISSUED', p_actor, r.target_user_id, v_meta || jsonb_build_object(
    'grant_expires_at', v_now + interval '30 minutes',
    'reissue', true));

  PERFORM public.g7f3c3_assert_target_revoked(r.target_user_id);
  IF public.g7f3c3_authority_snapshot(r.target_user_id) IS DISTINCT FROM v_before THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:authority_records_changed';
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'request_id', r.id,
    'status', 'executed_awaiting_enrolment',
    'target_user_id', r.target_user_id,
    'grant_expires_at', v_now + interval '30 minutes',
    'recovery_expires_at', r.expires_at
  );
END;
$$;

CREATE FUNCTION public.g7f3c3_redeem_impl(p_user uuid, p_session uuid, p_grant_hash text, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_request uuid;
  r public.platform_mfa_recovery_requests;
  v_check text;
  v_session_created timestamptz;
  v_attempts integer;
BEGIN
  IF p_user IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  SELECT l.request_id INTO v_request FROM public.platform_mfa_recovery_locks l WHERE l.user_id = p_user;
  IF NOT FOUND THEN
    RETURN public.g7f3c3_deny('redeem', 'no_recovery_in_progress', p_user, p_session, p_user, NULL, p_mode);
  END IF;
  r := public.g7f3c3_lock_request(v_request, false);
  IF r.id IS NULL OR r.target_user_id <> p_user THEN
    RETURN public.g7f3c3_deny('redeem', 'no_recovery_in_progress', p_user, p_session, p_user, v_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('redeem', 'request_expired', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  IF r.status <> 'executed_awaiting_enrolment' THEN
    RETURN public.g7f3c3_deny('redeem', 'recovery_not_awaiting_enrolment', p_user, p_session, p_user, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  IF r.grant_redeemed_at IS NOT NULL THEN
    RETURN public.g7f3c3_deny('redeem', 'grant_already_redeemed', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  IF r.grant_expires_at <= pg_catalog.now() THEN
    RETURN public.g7f3c3_deny('redeem', 'grant_expired', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  IF p_grant_hash IS NULL OR p_grant_hash !~ '^[0-9a-f]{64}$' OR p_grant_hash <> r.grant_hash THEN
    v_attempts := r.grant_failed_attempts + 1;
    UPDATE public.platform_mfa_recovery_requests
    SET grant_failed_attempts = v_attempts,
        grant_expires_at = CASE WHEN v_attempts >= 5 THEN LEAST(grant_expires_at, pg_catalog.now()) ELSE grant_expires_at END
    WHERE id = r.id;
    RETURN public.g7f3c3_deny('redeem', 'grant_mismatch', p_user, p_session, p_user, r.id, p_mode,
      jsonb_build_object('failed_attempts', v_attempts, 'grant_invalidated', v_attempts >= 5));
  END IF;
  v_check := public.g7f3c3_session_check(p_user, p_session, false, NULL);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('redeem', v_check, p_user, p_session, p_user, r.id, p_mode);
  END IF;
  SELECT s.created_at INTO v_session_created FROM auth.sessions s WHERE s.id = p_session;
  IF v_session_created IS NULL OR v_session_created <= r.grant_issued_at THEN
    RETURN public.g7f3c3_deny('redeem', 'session_predates_recovery', p_user, p_session, p_user, r.id, p_mode);
  END IF;

  UPDATE public.platform_mfa_recovery_requests
  SET grant_redeemed_at = pg_catalog.now(),
      redeemed_session_id = p_session
  WHERE id = r.id;

  PERFORM public.g7f3c3_audit('MFA_RECOVERY_GRANT_REDEEMED', p_user, p_user, jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));

  RETURN jsonb_build_object('ok', true, 'request_id', r.id, 'status', r.status, 'recovery_expires_at', r.expires_at);
END;
$$;

CREATE FUNCTION public.g7f3c3_complete_impl(p_user uuid, p_session uuid, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_request uuid;
  r public.platform_mfa_recovery_requests;
  v_check text;
  v_session_factor uuid;
  v_verified_count integer;
  v_factor uuid;
  v_factor_type text;
  v_factor_created timestamptz;
  v_factor_ids jsonb;
  v_before jsonb;
BEGIN
  IF p_user IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  SELECT l.request_id INTO v_request FROM public.platform_mfa_recovery_locks l WHERE l.user_id = p_user;
  IF NOT FOUND THEN
    RETURN public.g7f3c3_deny('complete', 'no_recovery_in_progress', p_user, p_session, p_user, NULL, p_mode);
  END IF;
  r := public.g7f3c3_lock_request(v_request, false);
  IF r.id IS NULL OR r.target_user_id <> p_user THEN
    RETURN public.g7f3c3_deny('complete', 'no_recovery_in_progress', p_user, p_session, p_user, v_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('complete', 'request_expired', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  IF r.status <> 'executed_awaiting_enrolment' THEN
    RETURN public.g7f3c3_deny('complete', 'recovery_not_awaiting_enrolment', p_user, p_session, p_user, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  IF r.grant_redeemed_at IS NULL THEN
    RETURN public.g7f3c3_deny('complete', 'grant_not_redeemed', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  IF p_session IS NULL OR p_session IS DISTINCT FROM r.redeemed_session_id THEN
    RETURN public.g7f3c3_deny('complete', 'session_not_redeemed_session', p_user, p_session, p_user, r.id, p_mode);
  END IF;
  v_check := public.g7f3c3_session_check(p_user, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('complete', v_check, p_user, p_session, p_user, r.id, p_mode);
  END IF;

  SELECT s.factor_id INTO v_session_factor FROM auth.sessions s WHERE s.id = p_session;
  SELECT count(*)::integer, COALESCE(jsonb_agg(f.id), '[]'::jsonb) INTO v_verified_count, v_factor_ids
  FROM auth.mfa_factors f WHERE f.user_id = p_user AND f.status::text = 'verified';
  IF v_verified_count = 1 THEN
    SELECT f.id, f.factor_type::text, f.created_at INTO v_factor, v_factor_type, v_factor_created
    FROM auth.mfa_factors f WHERE f.user_id = p_user AND f.status::text = 'verified';
  END IF;

  IF v_verified_count <> 1
     OR v_factor_type IS DISTINCT FROM 'totp'
     OR v_factor_created <= r.grant_redeemed_at
     OR v_session_factor IS DISTINCT FROM v_factor THEN
    -- Fail closed: unexpected factor state (e.g. a factor enrolled outside the redeemed flow).
    UPDATE public.platform_mfa_recovery_requests
    SET status = 'failed', terminal_reason = 'unexpected_factor_state'
    WHERE id = r.id;
    RETURN public.g7f3c3_deny('complete', 'unexpected_factor_state', p_user, p_session, p_user, r.id, p_mode,
      jsonb_build_object(
        'verified_factor_count', v_verified_count,
        'verified_factor_ids', v_factor_ids,
        'session_factor_id', v_session_factor,
        'factor_created_before_redemption', v_factor_created IS NOT NULL AND v_factor_created <= r.grant_redeemed_at,
        'flagged', true,
        'request_terminal', true,
        'target_remains_locked', true));
  END IF;

  v_before := public.g7f3c3_authority_snapshot(p_user);

  UPDATE public.platform_mfa_recovery_requests
  SET status = 'completed',
      completed_at = pg_catalog.now(),
      replacement_factor_id = v_factor
  WHERE id = r.id;

  DELETE FROM public.platform_mfa_recovery_locks WHERE user_id = p_user AND request_id = r.id;

  PERFORM public.g7f3c3_audit('MFA_REPLACEMENT_ENROLLED', p_user, p_user, jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'replacement_factor_id', v_factor,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));
  PERFORM public.g7f3c3_audit('MFA_RECOVERY_COMPLETED', p_user, p_user, jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'replacement_factor_id', v_factor,
    'executed_at', r.executed_at,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));

  IF public.is_platform_mfa_recovery_locked(p_user) THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:lock_remains';
  END IF;
  IF public.g7f3c3_authority_snapshot(p_user) IS DISTINCT FROM v_before THEN
    RAISE EXCEPTION 'g7f3c3_postcondition_failed:authority_records_changed';
  END IF;

  RETURN jsonb_build_object('ok', true, 'request_id', r.id, 'status', 'completed', 'replacement_factor_id', v_factor);
END;
$$;

CREATE FUNCTION public.g7f3c3_cancel_impl(p_actor uuid, p_session uuid, p_request uuid, p_reason text, p_mode text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  r public.platform_mfa_recovery_requests;
  v_check text;
  v_basis text;
  v_reason text := NULLIF(btrim(COALESCE(p_reason, '')), '');
BEGIN
  IF p_actor IS NULL OR p_request IS NULL THEN
    RAISE EXCEPTION 'invalid_mfa_recovery_args' USING ERRCODE = 'invalid_parameter_value';
  END IF;
  r := public.g7f3c3_lock_request(p_request, false);
  IF r.id IS NULL THEN
    RETURN public.g7f3c3_deny('cancel', 'request_not_found', p_actor, p_session, NULL, p_request, p_mode);
  END IF;
  IF public.g7f3c3_expire_if_due(r, p_mode) THEN
    RETURN public.g7f3c3_deny('cancel', 'request_expired', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF r.status = 'executed_awaiting_enrolment' THEN
    RETURN public.g7f3c3_deny('cancel', 'cannot_cancel_after_execution', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF r.status NOT IN ('requested', 'approved') THEN
    RETURN public.g7f3c3_deny('cancel', 'request_terminal', p_actor, p_session, r.target_user_id, r.id, p_mode,
      jsonb_build_object('status', r.status));
  END IF;
  v_check := public.g7f3c3_session_check(p_actor, p_session, true, 300);
  IF v_check IS NOT NULL THEN
    RETURN public.g7f3c3_deny('cancel', v_check, p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF p_actor = r.target_user_id THEN
    IF public.is_platform_mfa_recovery_locked(p_actor) OR NOT public.g7f3c3_has_verified_totp(p_actor) THEN
      RETURN public.g7f3c3_deny('cancel', 'actor_cannot_cancel', p_actor, p_session, r.target_user_id, r.id, p_mode);
    END IF;
    v_basis := 'target';
  ELSIF public.g7f3c3_usable_normal_so(p_actor) THEN
    v_basis := 'normal_super_owner';
  ELSIF public.g7f3c3_usable_bg(p_actor) THEN
    v_basis := 'break_glass';
  ELSE
    RETURN public.g7f3c3_deny('cancel', 'actor_cannot_cancel', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;
  IF v_reason IS NOT NULL AND length(v_reason) > 500 THEN
    RETURN public.g7f3c3_deny('cancel', 'reason_invalid', p_actor, p_session, r.target_user_id, r.id, p_mode);
  END IF;

  UPDATE public.platform_mfa_recovery_requests
  SET status = 'cancelled',
      cancelled_at = pg_catalog.now(),
      cancelled_by = p_actor,
      terminal_reason = 'cancelled_by_' || v_basis
  WHERE id = r.id;

  PERFORM public.g7f3c3_audit('MFA_RECOVERY_CANCELLED', p_actor, r.target_user_id, jsonb_build_object(
    'request_id', r.id,
    'target_kind', r.target_kind,
    'previous_status', r.status,
    'cancel_basis', v_basis,
    'reason', v_reason,
    'actor_session_fp', public.g7f3c3_fp(p_session),
    'mode', public.g7f3c3_mode(p_mode)
  ));

  RETURN jsonb_build_object('ok', true, 'request_id', r.id, 'status', 'cancelled', 'cancel_basis', v_basis);
END;
$$;

CREATE FUNCTION public.g7f3c3_expire_sweep_impl(p_mode text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_id uuid;
  r public.platform_mfa_recovery_requests;
  v_count integer := 0;
BEGIN
  FOR v_id IN
    SELECT id FROM public.platform_mfa_recovery_requests
    WHERE status IN ('requested', 'approved', 'executed_awaiting_enrolment') AND expires_at <= pg_catalog.now()
  LOOP
    r := public.g7f3c3_lock_request(v_id, false);
    IF public.g7f3c3_expire_if_due(r, p_mode) THEN
      v_count := v_count + 1;
    END IF;
  END LOOP;
  RETURN v_count;
END;
$$;

-- ---------------------------------------------------------------------------------------------
-- 9. Public RPCs (service_role only)
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION public.request_platform_mfa_recovery(
  p_actor_user_id uuid, p_actor_session_id uuid, p_target_user_id uuid, p_reason text,
  p_cooling_off_minutes integer, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_request_impl(p_actor_user_id, p_actor_session_id, p_target_user_id, p_reason, p_cooling_off_minutes, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.approve_platform_mfa_recovery(
  p_actor_user_id uuid, p_actor_session_id uuid, p_request_id uuid, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_approve_impl(p_actor_user_id, p_actor_session_id, p_request_id, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.execute_platform_mfa_recovery(
  p_actor_user_id uuid, p_actor_session_id uuid, p_request_id uuid, p_grant_hash text, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_execute_impl(p_actor_user_id, p_actor_session_id, p_request_id, p_grant_hash, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.reissue_platform_mfa_recovery_grant(
  p_actor_user_id uuid, p_actor_session_id uuid, p_request_id uuid, p_grant_hash text, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_reissue_impl(p_actor_user_id, p_actor_session_id, p_request_id, p_grant_hash, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.redeem_platform_mfa_recovery_grant(
  p_user_id uuid, p_session_id uuid, p_grant_hash text, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_redeem_impl(p_user_id, p_session_id, p_grant_hash, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.complete_platform_mfa_recovery(
  p_user_id uuid, p_session_id uuid, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_complete_impl(p_user_id, p_session_id, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.cancel_platform_mfa_recovery(
  p_actor_user_id uuid, p_actor_session_id uuid, p_request_id uuid, p_reason text DEFAULT NULL, p_mode text DEFAULT 'disabled'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v jsonb;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_cancel_impl(p_actor_user_id, p_actor_session_id, p_request_id, p_reason, p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

CREATE FUNCTION public.expire_platform_mfa_recovery_requests(p_mode text DEFAULT 'disabled')
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v integer;
BEGIN
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'on', true);
  v := public.g7f3c3_expire_sweep_impl(p_mode);
  PERFORM pg_catalog.set_config('g7f3c3.rpc', 'off', true);
  RETURN v;
END;
$$;

-- Own recovery state (target-facing). Never returns grant_hash or another user's data.
CREATE FUNCTION public.get_platform_mfa_recovery_self_state(p_user_id uuid, p_session_id uuid DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_lock public.platform_mfa_recovery_locks;
  r public.platform_mfa_recovery_requests;
  v_pending jsonb;
BEGIN
  IF p_user_id IS NULL THEN
    RETURN jsonb_build_object('locked', false);
  END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'request_id', q.id, 'status', q.status, 'target_kind', q.target_kind,
           'cooling_off_until', q.cooling_off_until, 'expires_at', q.expires_at,
           'created_at', q.created_at) ORDER BY q.created_at DESC), '[]'::jsonb)
    INTO v_pending
  FROM public.platform_mfa_recovery_requests q
  WHERE q.target_user_id = p_user_id AND q.status IN ('requested', 'approved');

  SELECT * INTO v_lock FROM public.platform_mfa_recovery_locks WHERE user_id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('locked', false, 'pending_requests', v_pending);
  END IF;
  SELECT * INTO r FROM public.platform_mfa_recovery_requests WHERE id = v_lock.request_id;
  RETURN jsonb_build_object(
    'locked', true,
    'request_id', r.id,
    'status', CASE WHEN r.status = 'executed_awaiting_enrolment' AND pg_catalog.now() >= r.expires_at
                   THEN 'expired' ELSE r.status END,
    'target_kind', r.target_kind,
    'executed_at', r.executed_at,
    'recovery_expires_at', r.expires_at,
    'grant_expires_at', r.grant_expires_at,
    'grant_usable', r.status = 'executed_awaiting_enrolment' AND r.grant_redeemed_at IS NULL
                    AND r.grant_expires_at > pg_catalog.now() AND r.expires_at > pg_catalog.now(),
    'grant_redeemed', r.grant_redeemed_at IS NOT NULL,
    'grant_redeemed_at', r.grant_redeemed_at,
    'redeemed_by_this_session', p_session_id IS NOT NULL AND r.redeemed_session_id = p_session_id,
    'pending_requests', v_pending
  );
END;
$$;

-- ---------------------------------------------------------------------------------------------
-- 10. Grants: nothing to PUBLIC / anon / authenticated; public RPCs to service_role only
-- ---------------------------------------------------------------------------------------------
DO $grants$
DECLARE
  f text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'public.g7f3c3_guard_recovery_write()',
    'public.g7f3c3_validate_recovery_transition()',
    'public.g7f3c3_fp(uuid)',
    'public.g7f3c3_mode(text)',
    'public.g7f3c3_has_role(uuid, text)',
    'public.g7f3c3_has_verified_totp(uuid)',
    'public.g7f3c3_in_recovery(uuid)',
    'public.g7f3c3_usable_normal_so(uuid)',
    'public.g7f3c3_usable_bg(uuid)',
    'public.g7f3c3_target_kind(uuid)',
    'public.g7f3c3_final_path_formula(integer, integer, text)',
    'public.g7f3c3_final_path_counts(uuid)',
    'public.g7f3c3_final_path_ok(uuid, text)',
    'public.g7f3c3_session_check(uuid, uuid, boolean, integer)',
    'public.g7f3c3_audit(text, uuid, uuid, jsonb)',
    'public.g7f3c3_deny(text, text, uuid, uuid, uuid, uuid, text, jsonb)',
    'public.g7f3c3_lock_target(uuid, boolean)',
    'public.g7f3c3_lock_request(uuid, boolean)',
    'public.g7f3c3_expire_if_due(public.platform_mfa_recovery_requests, text)',
    'public.g7f3c3_authority_snapshot(uuid)',
    'public.g7f3c3_revoke_target_auth(uuid)',
    'public.g7f3c3_assert_target_revoked(uuid)',
    'public.g7f3c3_request_impl(uuid, uuid, uuid, text, integer, text)',
    'public.g7f3c3_approve_impl(uuid, uuid, uuid, text)',
    'public.g7f3c3_execute_impl(uuid, uuid, uuid, text, text)',
    'public.g7f3c3_reissue_impl(uuid, uuid, uuid, text, text)',
    'public.g7f3c3_redeem_impl(uuid, uuid, text, text)',
    'public.g7f3c3_complete_impl(uuid, uuid, text)',
    'public.g7f3c3_cancel_impl(uuid, uuid, uuid, text, text)',
    'public.g7f3c3_expire_sweep_impl(text)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated, service_role', f);
  END LOOP;

  FOREACH f IN ARRAY ARRAY[
    'public.is_platform_mfa_recovery_locked(uuid)',
    'public.request_platform_mfa_recovery(uuid, uuid, uuid, text, integer, text)',
    'public.approve_platform_mfa_recovery(uuid, uuid, uuid, text)',
    'public.execute_platform_mfa_recovery(uuid, uuid, uuid, text, text)',
    'public.reissue_platform_mfa_recovery_grant(uuid, uuid, uuid, text, text)',
    'public.redeem_platform_mfa_recovery_grant(uuid, uuid, text, text)',
    'public.complete_platform_mfa_recovery(uuid, uuid, text)',
    'public.cancel_platform_mfa_recovery(uuid, uuid, uuid, text, text)',
    'public.expire_platform_mfa_recovery_requests(text)',
    'public.get_platform_mfa_recovery_self_state(uuid, uuid)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', f);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', f);
  END LOOP;
END;
$grants$;
